### ISSUE TITLE
Post MQ v9.1.1 queue metrics are loading

### ISSUE THREAD

**Issue by P9110963** [ibm-messaging/mq-metric-samples#10]
used the new MQ Sample metrics along with MQ v9.1.1 post build few MQ queue metrics are not working. 

ex: ibmmq_object_mqget & ibmmq_object_mqput

Used the below Prometheus scripts to collect the queue and channel metrics. 

===================================
#!/bin/sh

# This is used to start the IBM MQ monitoring service for Prometheus

# The queue manager name comes in from the service definition as the
# only command line parameter
qMgr=$1

# Set the environment to ensure we pick up libmqm.so etc
. /opt/mqm/bin/setmqenv -m $qMgr -k

# A list of queues to be monitored is given here.
# It is a set of names or patterns ('*' only at the end, to match how MQ works),
# separated by commas. When no queues match a pattern, it is reported but
# is not fatal.
queues="*"

# An alternative is to have a file containing the patterns, and named
# via the ibmmq.monitoredQueuesFile option.

# See config.go for all recognised flags

# A list of queues to be monitored is given here.
channels="*"

# Start via "exec" so the pid remains the same. The queue manager can
# then check the existence of the service and use the MQ_SERVER_PID value
# to kill it on shutdown.
#exec /usr/local/bin/mq_prometheus -ibmmq.queueManager=$qMgr -ibmmq.monitoredQueues="$queues" -log.level=error
exec /usr/local/bin/mq_prometheus -ibmmq.queueManager=$qMgr -ibmmq.monitoredQueues="$queues" -ibmmq.monitoredChannels="$channels" -log.level=error -ibmmq.qStatus=true

===========================================

**Comment by ibmmqmet** [comment]
what does "not working" mean?

**Comment by P9110963** [comment]
Hi,

Got it working.  All our dashboards were configured with ibmmq_object for queue metrics. Where the new queue metrics are available in ibmmq_queue
