### ISSUE TITLE
Deadletter queue is full

### ISSUE THREAD

**Issue by pakkinai** [ibm-messaging/mq-metric-samples#102]
**Hi**

    I would like to ask you about Deadletter queue is full more information as below.
- mq-metrics-samples version : 5.2.3
- IBM MQ : 9.0.4.0
- Env : Linux

Service :
DEFINE SERVICE(MQPROMETHEUS)         +
       CONTROL(QMGR)               +
       SERVTYPE(SERVER)            +
       STARTCMD('/opt/zabbix/zabbix_agent/scripts/mqgo/bin/mq_prometheus.sh') +
       STARTARG(+QMNAME+)          +
       STOPCMD('/usr/bin/kill ' )  +
       STOPARG(+MQ_SERVER_PID+)    +
       STDOUT('/opt/zabbix/zabbix_agent/scripts/mqgo/logs/mq_prometheus.out')  +
       STDERR('/opt/zabbix/zabbix_agent/scripts/mqgo/logs/mq_prometheus.out')  +
       DESCR('MQ exporter for Prometheus')

    I have found the problem in term of the first time implement this exporter and  zabbix that connect with prometheus exporter is down that make the Deadletter queue is full  5000 messages
**Case 1 : Fisrt time implement exporter >** DLQ full at 5000 message and wait for awhile , After that can consume to be 0 automatically.
**Case 2 : zabbix that connect with prometheus exporter is down >** DLQ full at 5000 message , After start zabbix can consume to be 0 as well.

    Therefore , I tried to set following your suggestion on Readme by set :
> ALTER TOPIC(SYSTEM.ADMIN.TOPIC) USEDLQ(NO)
   I just would like to know any consequence effect to another queue or QMGR for this setting ?

**Comment by ibmmqmet** [comment]
Setting that option will only affect publications in the $SYS/MQ topic tree, so should not make any difference for any other topics that applications might be publishing on

**Comment by pakkinai** [comment]
I see . Is that affect to performance of zabbix monitoring in case of delay of data. or lost the message ?

**Comment by ibmmqmet** [comment]
I don't really understand your question. 

The behaviour of the USEDLQ option is in the [MQ documentation](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=reference-define-topic-define-new-administrative-topic). For these admin publications, the qmgr will likely ignore any returned error code, so the messages are effectively discarded.

**Comment by pakkinai** [comment]
sorry one question. On my environment , I have a lot of QM and each QM have many queue also.
How can I increase the size of subscription > $SYS/MQ ? for saving and handling messages as much as possible before send message to DLQ.

**Comment by ibmmqmet** [comment]
The MAXDEPTH on the configured MODELQ definitions that are used for creating the subscription determines how many publications can be held before things go to the DLQ. 

If you've not done any explicit config then it will refer to SYSTEM.DEFAULT.MODEL.QUEUE which has a default value of 5000.
