### ISSUE TITLE
Checking QMGR Status

### ISSUE THREAD

**Issue by piotrekbed** [ibm-messaging/mq-metric-samples#11]
Hi, 
Which metric records the current status of QMGR?
Now I'm checking if it running  doing something like that "count(ibmmq_qmgr_commit_count)" 
There is another way? 
I'm using c972b14 (the latest). 

BR

**Comment by ibmmqmet** [comment]
What do you mean by status? If the bridge is connected to the queue manager and producing statistics, then the queue manager is running; if it's not connected, then it isn't! 

There's no external check like running the "dspmq" command. Everything in these monitor is done by using MQ messages put/got on queues.

**Comment by piotrekbed** [comment]
I need something like: 
DISPLAY QMSTATUS ALL

**Comment by ibmmqmet** [comment]
But which fields are actually interesting metrics from that command? Perhaps the Channel Initiator status. Perhaps the connection count (though that includes internal processes). The fact that other metrics are being delivered to grafana produced is proof that the queue manager and command server are running.

**Comment by ibmmqmet** [comment]
Latest version adds fields that can be used as metrics from several object types - SBSTATUS, TPSTATUS, QMSTATUS
