### ISSUE TITLE
Connecting to QMGR over TLS

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-metric-samples#113]
Thank you for this great stuff!

What do I do in order to enable the metrics pod to connect to the QMGR running on CP4I over TLS; preferably with an option to pass the trusted certificates (one-way TLS) as a Kubernetes secret?

https://github.com/ibm-messaging/mq-metric-samples/tree/master/scripts
https://github.com/ibm-messaging/mq-metric-samples/tree/master/pkg/config

**Comment by ibmmqmet** [comment]
Setting up TLS in general for MQ apps is described here: https://developer.ibm.com/tutorials/mq-secure-msgs-tls/ That covers both the client and server side including ways to create the kdb keystore needed that holds both your personal cert and relevant CA certs to authenticate the server.

Specifically for the tools here, there's a ccdtUrl configuration option that allows you to point at the CCDT in either json or binary format. That file should have the TLS config for your chosen svrconn channel.

**Comment by abudavis** [comment]
> 

How do I introduce a CCDT file and a kdb keystore into the docker image that is being built using the below links as I understand the mq-metric pod would act as the client here?
https://github.com/ibm-messaging/mq-metric-samples/tree/master/scripts
https://github.com/ibm-messaging/mq-metric-samples/tree/master/cp4i

Would also be great if you could please point me to the ccdtUrl configuration option.

**Comment by ibmmqmet** [comment]
https://github.com/ibm-messaging/mq-golang-jms20/tree/main/tls-samples has more examples on how to create kdb keystores, using just MQ-provided commands rather than starting from the openssl versions on the tutorial page. 

Whether you run the scripts "locally" and then copy the kdb and sth files across as part of the Dockerfile, or whether you use `RUN` statements in the Dockerfile to build the contents as part of the container build process would be your choice, probably based on what you might have installed locally. 

The YAML config file does allow you to point at a CCDT. Fuller descriptions of what the CCDTURL looks like, and the JSON-style CCDT contents itself can be found https://www.ibm.com/docs/en/ibm-mq/9.2?topic=tables-url-access-ccdt and https://www.ibm.com/docs/en/ibm-mq/9.2?topic=ccdt-json-examples (the transmissionSecurity section). You;d likely also need the `MQSSLKEYR` environment variable that points at whereever you've put your keystore as it's not part of the CCDT.

Just about all of this is general, applicable to any MQ client application that's built on the C libraries. It's not specific to this repo. I might see about creating an additional sample script and Dockerfile if I get time, but it's not going to be immediate.

**Comment by abudavis** [comment]
I was able to get this up and running with mutual TLS enabled, I didn't have to re-build the docker image, just had to extend the metrics-pod.yaml, create secrets for holding certificates and configmaps for CCDT & mqclient.ini, here is my sample for reference - https://github.com/abudavis/mq-metric-samples/blob/master/cp4i/metrics-pod-tls.yaml

Some key observations: 

1. Setting the MQSSLKEYR did not work and kept reporting MQRC_KEY_REPOSITORY_ERROR [2381], I therefore had to create a mqclient.ini (see content below) and add as a ConfigMap:
```
SSL:
  SSLKeyRepository=/IBM/MQ/data/key
  SSLKeyResetCount=0
  OCSPAuthentication=OPTIONAL
  OCSPCheckExtensions=NO
  CDPCheckExtensions=NO
```

2. In my example, the following environment variables were set in the ConfigMap:
```
MQCCDTURL='file:///home/ccdt/ccdt.json'
MQCLNTCF='/home/mqclientini/mqclient.ini
```

The ConfigMap:
```
oc create configmap metrics-configuration \
    --from-literal=IBMMQ_CONNECTION_QUEUEMANAGER='QMGR1' \
    --from-literal=IBMMQ_OBJECTS_QUEUES='*,!SYSTEM.*,!AMQ.*' \
    --from-literal=IBMMQ_OBJECTS_CHANNELS='*,!SYSTEM.*' \
    --from-literal=IBMMQ_OBJECTS_SUBSCRIPTIONS='!$SYS*' \
    --from-literal=IBMMQ_OBJECTS_TOPICS='*,!SYSTEM.*' \
    --from-literal=IBMMQ_GLOBAL_USEPUBLICATIONS=true \
    --from-literal=IBMMQ_GLOBAL_USEOBJECTSTATUS=true \
    --from-literal=IBMMQ_GLOBAL_CONFIGURATIONFILE='' \
    --from-literal=MQCCDTURL='file:///home/ccdt/ccdt.json' \
    --from-literal=MQCLNTCF='/home/mqclientini/mqclient.ini' \
    --from-literal=IBMMQ_GLOBAL_LOGLEVEL=INFO

oc create secret generic metrics-credentials \
    --from-literal=IBMMQ_CONNECTION_USER='' \
    --from-literal=IBMMQ_CONNECTION_PASSWORD=''
```

4. In my example the following ccdt.json was used:

```
{
 "channel": [
  {
   "name": "METRICS",
   "clientConnection": {
    "connection": [
     {
      "host": "qmgr1-ibm-mq.mq.svc",
      "port": 1414
     }
    ],
    "queueManager": "QMGR1"
   },
   "transmissionSecurity":
   {
    "cipherSpecification": "ANY_TLS12_OR_HIGHER",
    "certificateLabel": "ibmwebspheremqmetrics"
   },
   "type": "clientConnection"
  }
 ]
}
```

5. To enable mutual TLS, the SVRCONN channel on the QMGR1 had the following setting:
`def chl(METRICS) CHLTYPE(SVRCONN) SSLCIPH(ANY_TLS12_OR_HIGHER) SSLCAUTH(REQUIRED)`

**Comment by ibmmqmet** [comment]
Thanks for that. I tend not to use the cp4i packaging options, as I stick to the base packages in a directly-controlled container, but it's very useful to see a worked configuration.

**Comment by scannerscan** [comment]
@ibmmqmet , I tried using the same approach to set up the monitor via TLS. For some reason, none of the env variables MQCCDTURL, MQCHLLIB, MQCHLTAB are getting set. No problem with MQCLNTCF though. Am I missing something?
ConfigMap part
`data:
  IBMMQ_CONNECTION_QUEUEMANAGER: 'QM1'
  IBMMQ_CONNECTION_CONNNAME: 'qm1-ibm-mq(1414)'
  IBMMQ_CONNECTION_CHANNEL: 'SYS.SVRCONN.MONITOR'
  IBMMQ_OBJECTS_QUEUES: '!SYSTEM.*,!AMQ.*,*'
  IBMMQ_OBJECTS_SUBSCRIPTIONS: "!$SYS*"
  IBMMQ_OBJECTS_TOPICS: "!$SYS*"
  IBMMQ_GLOBAL_USEPUBLICATIONS: 'true'
  IBMMQ_GLOBAL_USEOBJECTSTATUS: 'true'
  IBMMQ_GLOBAL_CONFIGURATIONFILE: ''
  IBMMQ_GLOBAL_LOGLEVEL: TRACE
  MQCCDTURL: file:///home/ccdt/ccdt.json
  MQCLNTCF: /home/mqclientini/mqclient.ini

---`
POD env output and logs:
`EPWBCSQM1_IBM_MQ_PORT_9443_TCP=tcp://10.43.82.205:9443
EPWBCSQM1_IBM_MQ_QM_PORT_1414_TCP_PORT=1414
EPWBCSQM1_IBM_MQ_QM_PORT_1414_TCP_PROTO=tcp
RDURL=https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist
IBMMQ_OBJECTS_TOPICS=!$SYS*
EPWBCSQM1_IBM_MQ_LOADBALANCER_PORT_9443_TCP_ADDR=10.43.41.50
EPWBCSQM1_IBM_MQ_QM_SERVICE_HOST=10.43.151.132
MONITOR=mq_prometheus
KUBERNETES_SERVICE_PORT_HTTPS=443
EPWBCSQM1_IBM_MQ_LOADBALANCER_PORT_1414_TCP=tcp://10.43.41.50:1414
EPWBCSQM1_IBM_MQ_WEB_PORT_9443_TCP=tcp://10.43.205.163:9443
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
EPWBCSQM1_IBM_MQ_LOADBALANCER_PORT_9443_TCP_PORT=9443
EPWBCSQM1_IBM_MQ_LOADBALANCER_SERVICE_PORT=1414
EPWBCSQM1_IBM_MQ_LOADBALANCER_PORT=tcp://10.43.41.50:1414
IBMMQ_OBJECTS_SUBSCRIPTIONS=!$SYS*
IBMMQ_CONNECTION_CONNNAME=qm1-ibm-mq(1414)
KUBERNETES_SERVICE_HOST=10.43.0.1
EPWBCSQM1_IBM_MQ_LOADBALANCER_PORT_9443_TCP_PROTO=tcp
EPWBCSQM1_IBM_MQ_SERVICE_PORT_QMGR=1414
PWD=/
EPWBCSQM1_IBM_MQ_METRICS_PORT_9157_TCP=tcp://10.43.159.24:9157
IBMMQ_GLOBAL_USEPUBLICATIONS=true
IBMMQ_OBJECTS_QUEUES=!SYSTEM.*,!AMQ.*,*
EPWBCSQM1_IBM_MQ_QM_PORT_1414_TCP=tcp://10.43.151.132:1414
EPWBCSQM1_IBM_MQ_QM_PORT=tcp://10.43.151.132:1414
EPWBCSQM1_IBM_MQ_QM_SERVICE_PORT=1414
IBMMQ_GLOBAL_LOGLEVEL=TRACE
MQCLNTCF=/home/mqclientini/mqclient.ini
IBM MQ metrics exporter for Prometheus monitoring
Build         : 20240703-164622
Commit Level  : 7608b1f
Build Platform: Linux/x86_64
MQ Go Version : v5.5.4
time="2024-07-03T07:33:36Z" level=debug msg="VerifyConfig Config: {cf:{ConfigFile: QMgrName:QM1 ReplyQ:SYSTEM.DEFAULT.MODEL.QUEUE ReplyQ2: MetaPrefix: TZOffsetString:0h Locale: MonitoredQueues:!SYSTEM.*,!AMQ.*,* MonitoredQueuesFile: MonitoredChannels: MonitoredChannelsFile: MonitoredAMQPChannels: MonitoredAMQPChannelsFile: MonitoredTopics:!$SYS* MonitoredTopicsFile: MonitoredSubscriptions:!$SYS* MonitoredSubscriptionsFile: QueueSubscriptionSelector: metadataTags: metadataValues: MetadataTagsArray:[] MetadataValuesArray:[] LogLevel:TRACE pollInterval:0s PollIntervalDuration:0 rediscoverInterval:1h RediscoverDuration:0 CC:{ClientMode:false UserId: Password: TZOffsetSecs:0 SingleConnect:false UsePublications:true UseStatus:true UseResetQStats:false ShowInactiveChannels:false HideSvrConnJobname:false HideAMQPClientId:false WaitInterval:3 CcdtUrl: ConnName:qm1-ibm-mq(1414) Channel:SYS.SVRCONN.MONITOR DurableSubPrefix:}} httpListenPort:9157 httpListenHost: httpMetricPath:/metrics namespace:ibmmq httpsCertFile: httpsKeyFile: keepRunning:true reconnectIntervalDuration:0 reconnectInterval:5s overrideCType: overrideCTypeBool:false}"
time="2024-07-03T07:33:36Z" level=debug msg="In main loop: qMgrConnected=false"
time="2024-07-03T07:33:36Z" level=trace msg="> [EndConnection]"
time="2024-07-03T07:33:36Z" level=trace msg="< [EndConnection] rp: 1"
time="2024-07-03T07:33:36Z" level=trace msg="> [initConnectionKey] : QMgrName QM1"
time="2024-07-03T07:33:36Z" level=trace msg="> [initConnection] : key: "
time="2024-07-03T07:33:36Z" level=trace msg="> [newConnectionInfo]"
time="2024-07-03T07:33:36Z" level=trace msg="< [newConnectionInfo] rp: 0 Key: @defaultConnection"
time="2024-07-03T07:33:36Z" level=trace msg="< [initConnection] rp: 0"
time="2024-07-03T07:33:36Z" level=info msg="Trying to connect as client using ConnName: qm1-ibm-mq(1414), Channel: SYS.SVRCONN.MONITOR"
time="2024-07-03T07:33:36Z" level=debug msg="Connecting to queue manager QM1"
time="2024-07-03T07:33:36Z" level=debug msg="HTTP server - waiting until MQ connection ready"
time="2024-07-03T07:33:36Z" level=trace msg="< [initConnectionKey] rp: 1 Error: MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_SSL_INITIALIZATION_ERROR [2393]"
time="2024-07-03T07:33:36Z" level=error msg="Connection to QM1 has failed. Cannot connect to queue manager EPWBCSQM1 : MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_SSL_INITIALIZATION_ERROR [2393]"
time="2024-07-03T07:33:36Z" level=info msg=Done.`

**Comment by scannerscan** [comment]
The problem is solved by adding -ibmmq.client=true' as an argument for the monitor. thanks
