### ISSUE TITLE
Does this project work for Windows ?

### ISSUE THREAD

**Issue by liuguiyu** [ibm-messaging/mq-metric-samples#12]
Please include the following information in your ticket.

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.

**Comment by ibmmqmet** [comment]
Essentially yes it should.

You'd have to provide suitable control files for the monitor programs to replace the .sh startup scripts and .mqsc service definitions but the Unix versions here are only examples anyway that are likely to have to be changed on real systems as well.

**Comment by liuguiyu** [comment]
Thanks for the feedback, given I am brand-new to those open source tools, probably I should start from Linux ( seems the guide is also for Linux )

**Comment by ibmmqmet** [comment]
There's more Windows instructions in the underlying mq-golang repository, and building the monitor programs is no different then than building the sample programs in that repo. But it's true that the dev and testing of these interfaces is done primarily on Linux.
