### ISSUE TITLE
Tagging Structure

### ISSUE THREAD

**Issue by mrytower05** [ibm-messaging/mq-metric-samples#129]
I'm currently using nri-prometheus to scrape the prometheus endpoint and send IBM MQ dimensional metrics up to New Relic. My issue is that historical tags from my IBM MQ Queues are getting sent up and I can't figure out where they are being added from. The config file for my IBM MQ Manager seems to be correct, but I'm curious to know if there is somewhere in the Prometheus configuration that I could be adding tags from? Does anyone know where you would add a config for tags of the MQ Queues, not necessarily the MQ Managers?

**Comment by ibmmqmet** [comment]
I don't really understand what you are asking. Particularly when you say "historical tags". The labels associated with each object's metrics are defined in the collector code, based on providing enough information to make them unique and provide key details to users. There's no real config to control those labels.

For example, see function _newMqGaugeVec_ in https://github.com/ibm-messaging/mq-metric-samples/blob/master/cmd/mq_prometheus/exporter.go
