### ISSUE TITLE
Channel statistics metrics availability

### ISSUE THREAD

**Issue by P9110963** [ibm-messaging/mq-metric-samples#13]
Hi, 

We use the latest mq-golang version of 4.0.5 where we could only see the below metrics for channels.  If we enable the channel statistics, we couldn't get enough metrics to pick them in prometheus. Hope this would be added in the upcoming version. It is worth keeping this issue open until we add this channel statistics metrics.  

ibmmq_channel_instance_type
ibmmq_channel_messages
ibmmq_channel_status
ibmmq_channel_status_squash
ibmmq_channel_substate
ibmmq_channel_time_since_msg
ibmmq_channel_type

Please include the following information in your ticket.

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.

**Comment by ibmmqmet** [comment]
I don't understand what you are asking here. Are you looking for more metrics from channels? If so, which? Are you saying you are not getting stats that you are expecting?

**Comment by P9110963** [comment]
Hi Mark, Let me give more clarity on the issue which we have. We are enabling MQ channels statistics at QMGR level and the statistics pushed to "SYSTEM.ADMIN.STATISTICS.QUEUE" which is not looked by our existing MQ prometheus exporter. This statistics provide more analysis in terms on no.of batches completed and incomplete batches etc., I would like to understand whether this can be expected by the upcoming releases.

**Comment by ibmmqmet** [comment]
If a value is returned from the DISPLAY CHSTATUS command then it might be possible to add it. 

But I would not expect to ever try to parse events put to the S.A.STATISTICS/ACCOUNTING.Q. So if something is only available from that source, then it is not going to be added to the Prometheus collector. For example, incomplete batches is not something that CHSTATUS shows.

**Comment by ibmmqmet** [comment]
Added some more of attributes from CHSTATUS, which does include some batch information (though not "incomplete")

**Comment by robsonpeixoto** [comment]
Hi @ibmmqmet . How can I interpret the ibmmq_channel_messages value? Why is it a gauge but not a counter?
