### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by hamid-vakil** [ibm-messaging/mq-metric-samples#131]
I install recently recently. when the docker is started, logs: 
level=error msg="Connection to BACKENDQM has failed. Cannot connect to queue manager BACKENDQM : MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CHANNEL_CONFIG_ERROR [2539]"

But any change on mq_prometheus.yaml has no effect! what is my fault?

- mq-metrics-samples version:5.2.5
- mq_prometheus.yaml file variations:
connection:
    queueManager: BACKENDQM
    ccdtUrl:
    connName: 10.10.17.142(1718)
    channel: PWA2SMS_CHN
    clientConnection: false
    replyQueue: SYSTEM.DEFAULT.MODEL.QUEUE
    clientConnection: false
    user: myID
    password: myPass

**Comment by ibmmqmet** [comment]
The product documentation tells you more about that error code and where to look next. See https://www.ibm.com/docs/en/ibm-mq/9.2?topic=codes-2539-09eb-rc2539-mqrc-channel-config-error 

Unless you provide the error log information, there's not much more that can be said.

**Comment by hamid-vakil** [comment]
Are there any other settings besides the mq_prometheus.yaml? What before and after dockerization?

**Comment by ibmmqmet** [comment]
You have still not provided any information from either the MQ client or queue manager error logs (AMQERR*.LOG). 

While it's possible that you might need to provide additional channel configuration such as TLS options via a [CCDT](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=server-configuring-client-channel-definition-tables), noone can be sure without knowing the details of what your error is.

**Comment by hamid-vakil** [comment]
would you please help me to find this log file (AMQERR*.LOG) on client side?

**Comment by ibmmqmet** [comment]
Usually under /var/mqm/errors or $HOME/IBM/MQ/data/errors. But a `find / -name AMQERR*` command should have found it easily enough
