### ISSUE TITLE
subscriptino queu growing when metrics not grabbed

### ISSUE THREAD

**Issue by julienmmm** [ibm-messaging/mq-metric-samples#15]
Hello,

I've beginning to play with the mq prometheus exporter and it works fine. However I've noticed that the queue created by the managed subscription (AMQ.....) was  read only when the metrics were grabbed and as the dynamic queu depth is only 5000 it becomes quickly full when prometheus is stopped. 
Is there a way to  change this behaviour?

Thanks!

**Comment by ibmmqmet** [comment]
You can't change that behaviour - the queue manager will continue to generate publications all the time the exporter program is connected. The queue filling up is not actually harmful, other than that when things do recover you'd get stale/incorrect data for the next collection. The only way to stop the messages being published is to stop the exporter.

There is a calculation done to give you a warning during startup if the maxdepth of the target queue seems too low - based on a one-minute collection time. So if Prometheus is down longer than that, then the queue may fill up. The calculation is based on the number of queues that are being monitored.

You can change the maxdepth of the queue receiving the publicatons, either by using a different model queue (a parameter to the exporter program) or by changing the value on the SYSTEM.DEFAULT.MODEL.QUEUE.
