### ISSUE TITLE
Run mq_prometheus detached?

### ISSUE THREAD

**Issue by pnvnd** [ibm-messaging/mq-metric-samples#152]
I'm currently running IBM MQ in Windows and `mq_prometheus.exe` works wonderfully.  I get all the metrics I need and it does what I expect it to do.

However, when I run `mq_prometheus.exe ` there is no way for me to run this in the background.  In Linux, I was able to use `nohup` to run things in the background, but in Windows, I tried:
- creating a Windows Service, but service doesn't start
- running a `.bat` file in the Startup folder, but terminal closes immediately
- running using the `START "" /B mq_prometheus.exe` but it stops when the command prompt is closed

Can a feature be added, like a switch or parameter, that allows `mq_prometheus.exe` to run detached or in the background?
![image](https://user-images.githubusercontent.com/65086728/186946089-5a02b68b-9077-455f-80a3-4b842200651f.png)

**Comment by sri1236** [comment]
Hi Peter  you can create Service object inside the queue manager and you can you can run these.

By the way i was facing some issue while configuring in Linux. can you please help on these.

**Comment by pnvnd** [comment]
@sri1236 What issues were you having?  For Linux, did you `export MQ_ENABLE_METRICS=true` to create an environment variable?  I've mostly followed the instructions [here](https://blog.jeroenmaes.eu/2020/08/building-and-running-the-ibm-mq_prometheus-collector-on-windows/), otherwise, check out [my configuration file](https://github.com/pnvnd/mq-metric-samples/releases/download/2022.08.29/mq_prometheus.yaml) and [my notes for Windows](https://github.com/pnvnd/mq-metric-samples/releases/download/2022.08.29/mq_prometheus.txt).

**Comment by ibmmqmet** [comment]
When monitoring local queue managers, the usual advice is to use an MQ Service definition so the queue manager controls the lifetime of the monitor.

For remote queue managers, you should be able to use the Windows Task Scheduler interface to create a job that starts the monitor in the background (just make sure to turn off the "kill job if it runs too long" option). Before Windows 10, I'd probably have used the _svrany_ program to run as a Windows Service, but that seems to have disappeared from current toolkits.

**Comment by grbabu234** [comment]
@pnvnd we  i also facing few error while compiling the code in Linux server(REDHAT). If possible can you please give the step by step installations including screen shot it will really help for us.

**Comment by pnvnd** [comment]
@grbabu234 I've compiled Linux binaries on Ubuntu 20.04.05 (WSL2) and can be found [here](https://github.com/pnvnd/mq-metric-samples/releases/tag/2022.08.30).

The steps in general are [the same as Windows](https://blog.jeroenmaes.eu/2020/08/building-and-running-the-ibm-mq_prometheus-collector-on-windows/)

1. [Install Go for Linux manually](https://go.dev/doc/install), since this needs at least Go v.1.17 to compile
2. [Install IBM MQ for Ubuntu](https://developer.ibm.com/tutorials/mq-connect-app-queue-manager-ubuntu/), Note, you may get some errors like `Download is performed unsandboxed as root as file '/root/MQServer/./InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)` and I was able to fix that with (these instructions)[https://askubuntu.com/questions/954862/couldnt-be-accessed-by-user-apt-pkgacquirerun-13-permission-denied].
3. cd into `./mq-metric-samples/cmd/mq_prometheus` and compile with `go build -o ./bin/mq_prometheus`
4. run `mq_prometheus -f mq_prometheus.yaml`

**Comment by sri1236** [comment]
@pnvnd  still facing few issues while compiling the code . If possible can we have quick video call for sort these issue. I am trying in Amazon ec2 instance. it will great help for me. if you are ok. Thanks
