### ISSUE TITLE
Export IBM i MQ metrics to Grafana

### ISSUE THREAD

**Issue by manuelcribeiro** [ibm-messaging/mq-metric-samples#160]
Hi
I was working on a way to export IBM i MQ metrics to a prometheus DB using python when I came across this video: https://www.youtube.com/watch?v=dCTTZWh5NDw
Is it possible to produce the same results with IBM i? As far as I know it isn't possible to run golang on IBM i.
I believe it is possible to run the collector remotely but is there noobs guide to on how to achieve this?

Thank you for your help

**Comment by ibmmqmet** [comment]
You should be able to run the collector on a different system (eg a Linux image) and connect as an MQ client. At its simplest, you only need to provide the channel and connection name to the qmgr in the config file, similar to any other MQ client configuration.
