### ISSUE TITLE
Docs regarding mTLS and TLS

### ISSUE THREAD

**Issue by paologallinaharbur** [ibm-messaging/mq-metric-samples#162]
I faced some issues building up a dev environment with having mTLS.

I ended up with a working [docker compose ](https://github.com/newrelic/newrelic-prometheus-exporters-packages/blob/main/exporters/ibmmq/e2e/docker-compose-tls.yml) and with the exporter leveraging two environment variables (MQCCDTURL and IBMMQ_CONNECTION_CCDTURL)which usage is a bit undocumented. 

I think that adding a section covering how to set up mTLS and TLS can help a lot.

**Comment by ibmmqmet** [comment]
See `runMonitorTLS.sh` in the scripts directory for an example including a CCDT
