### ISSUE TITLE
Passwordless configuration, is it supported?

### ISSUE THREAD

**Issue by paologallinaharbur** [ibm-messaging/mq-metric-samples#163]
I have been trying to understand if passwordless configuration is supported by the exporter. 

According to the docs setting ` --ibmmq.password` is not a requirement since "it can be set". 

However, if it is not set the exporter ignores `-ibmmq.userid` and tries to connect using the username that is executing the exporter. 
Moreover, even if the queue manager is not requiring password authentication and the userID is correct the exporter seems not to be able to connect and the following message is visualised:
```
Connection to QM1 has failed. Cannot connect to queue manager QM1 : MQCONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_NOT_AUTHORIZED [2035] 
```

**Comment by ibmmqmet** [comment]
The exporter documentation says
>  The password can be set either by using the `-ibmmq.password` flag, or by passing it via stdin.

But overall this is nothing really to do with the exporter. This is standard MQ queue manager behaviour. You cannot simply assert a userid from an MQ client. 

You  either provide credentials that can be authenticated (userid/password), or you rely on other configuration capabilities for the client including:
* MCAUSER setting on the SVRCONN definition
* CHLAUTH user or TLS mapping rules 
* Channel exits
* In the absence of anything else, the userid under which the client program is running will be used for the connection

**Comment by paologallinaharbur** [comment]
Thanks for the reply! 

I was able to make it working: 
I was confused by the fact that without a password it was using the userid under which the client program was running and not the one specified in the args.
