### ISSUE TITLE
Distinction between local and remote queues possible?

### ISSUE THREAD

**Issue by Bert99Blib** [ibm-messaging/mq-metric-samples#169]
Hello Mark,

we are currently still using version 5.2.4 against MQ version 9.2.0.6 on multiplatform and have the requirement to distinguish between 'local' and 'remote' queues in Grafana.

When I look at the metric 'ibmmq_queue_attribute_usage', I can only distinguish between 'nomal' and 'xmit' here (Value = 0 or 1) .

Maybe I just made a thinking error or didn't find the right metric ... is the distinction between local and remote over the mq-metric-samples currently possible? If not, are there any plans to include this in future versions?

Thanks in advance for your answer.

**Comment by ibmmqmet** [comment]
The queue manager only produces status and statistics for local queues. So there's nothing that can be reported here.

**Comment by Bert99Blib** [comment]
Thus a thinking error from my side - thanks for your quick reply.
