### ISSUE TITLE
Not working us if port is different to default in zOS

### ISSUE THREAD

**Issue by garrotemar** [ibm-messaging/mq-metric-samples#17]
We are trying to monitor MQ in zOS.
From a linux servers we are configuring:
export MQSERVER = 'APP1.CH.MVS/TCP/zoshost(1415)'
mq_prometheus.sh MQ1

Note: The channel, zoshost, port and queue manager are correct.

The error that throws us is the following:

AMQ7048: The queue manager name is either not valid or not known.
IBM MQ metrics exporter for Prometheus monitoring
FATA [0030] MQGET: MQCC = MQCC_FAILED [2] MQRC = MQRC_NO_MSG_AVAILABLE [2033]

When we use the default port (1414) it works correctly and we can obtain metrics.

**Comment by ibmmqmet** [comment]
The AMQ message is coming from the setmqenv call in the script - it's trying to set up LD_LIBRARY_PATH etc but the queue manager is not a local one so it fails. I will probably do something to mask that particular error, but you'd get a more serious problem if the MQ libraries could not then be found.

So you ARE connecting to the qmgr. Because otherwise you wouldn't have got a 2033 which can only come after opening a queue. But I can't tell why that is happening. Perhaps turning on the info or debug levels of logging would show more.

**Comment by garrotemar** [comment]
Thank you Mark for your response:
We set the log level to debug, but the output messages not help us:
AMQ7048: The queue manager name is either not valid or not known.
IBM MQ metrics exporter for Prometheus monitoring
DEBU[0000] Monitored topics are '#'                     
INFO[0000] Connected to queue manager  CSQ2             
FATA[0030] MQGET: MQCC = MQCC_FAILED [2] MQRC = MQRC_NO_MSG_AVAILABLE [2033] 

From zOS MQ are observed messages in the dead letter queue
DLH .......3AMQ.D666228449CC74E3                            CSQ2 
DLH .......3AMQ.D666228449CC74E3                            CSQ2 

Regards ... Marcelo

**Comment by ibmmqmet** [comment]
If there are messages in the DLQ, then the important field is going to be the reason code that shows why they were put there,

**Comment by garrotemar** [comment]
The messages in the dead letter queue are these, we can not identify what causes them:
View             CSQ2:CSQ2.DEAD.QUEUE            +                 Top of 2    
Command ===>                                                       Scroll CSR  
      Col 1         Insert Length 4194304        Record AT TOP     Format HEX                                                                                 
****** ****  Top of data  ****                                                
000001 DLH .......3AMQ.D6752F9683A49DE0                            CSQ2        
       CDC40000000FCDD4CFFFFCFFFFCFFCCF4444444444444444444444444444CEDF44444444
       438000010073148B46752696831494500000000000000000000000000000328200000000
       ----+----10---+----2----+----3----+----4----+----5----+----6----+----7--
                                                                               
000002 DLH .......3AMQ.D6752F9683A49DE0                            CSQ2        
       CDC40000000FCDD4CFFFFCFFFFCFFCCF4444444444444444444444444444CEDF44444444
       438000010073148B46752696831494500000000000000000000000000000328200000000
       ----+----10---+----2----+----3----+----4----+----5----+----6----+----7--
                                                                               
****** ****  End of data  ****                                                
View             CSQ2:CSQ2.DEAD.QUEUE            +                 Top of 2    
Command ===>                                                       Scroll CSR  
      Col 73        Insert Length 4194304        Record AT TOP     Format HEX  
                                                                               
****** ****  Top of data  ****                                                
000001                                     .......4MQADMIN ....CSQ2            
       4444444444444444444444444444444444440001000FDDCCDCD40000CEDF444444444444
       000000000000000000000000000000000000003100144814495000073282000000000000
       --+----80---+----9----+----100--+----1----+----2----+----3----+----4----
                                                                               
000002                                     .......4MQADMIN ....CSQ2            
       4444444444444444444444444444444444440001000FDDCCDCD40000CEDF444444444444
       000000000000000000000000000000000000003100144814495000073282000000000000
       --+----80---+----9----+----100--+----1----+----2----+----3----+----4----
                                                                               
****** ****  End of data  ****                                                
View             CSQ2:CSQ2.DEAD.QUEUE            +                 Top of 2    
Command ===>                                                       Scroll CSR  
      Col 145       Insert Length 4194304        Record AT TOP     Format HEX  
                                                                               
****** ****  Top of data  ****                                                
000001             2019072210392660...............................3............
       444444444444FFFFFFFFFFFFFFFF0001000200000001000000000000000F000000000002
       000000000000201907221039266000010004000300020001000000020073000200090008
       +----150--+----6----+----7----+----8----+----9----+----200--+----1----+-
                                                                               
000002             2019072210392660...............................{............
       444444444444FFFFFFFFFFFFFFFF0001000200000001000000000000000C000000000002
       0000000000002019072210392660000300040003000200020001000200B0000200090008
       +----150--+----6----+----7----+----8----+----9----+----200--+----1----+-
                                                                               
****** ****  End of data  ****                                                
View             CSQ2:CSQ2.DEAD.QUEUE            +                 Top of 2    
Command ===>                                                       Scroll CSR  
      Col 217       Insert Length 4194304        Record AT TOP     Format HEX  
                                                                               
****** ****  Top of data  ****                                                
000001 ...*....CSQ CSQ2   RCSQ2O..oh..................4....CSQ2                
       00150001CED4CEDF444DCEDFD7298D8000000004000F000F0003CEDF4444444444444444
       00BC0008328032820009328265F68EFC0004000400BE0014000032820000000000000000
       ---220--+----3----+----4----+----5----+----6----+----7----+----8----+---
                                                                               
000002 ...*....CSQ CSQ2   RCSQ2O..oh..................4....CSQ2                
       00150001CED4CEDF444DCEDFD7298D8000000004000F000F0003CEDF4444444444444444
       00BC0008328032820009328265F68EFC0004000400BE0014000032820000000000000000
       ---220--+----3----+----4----+----5----+----6----+----7----+----8----+---
                                                                               
****** ****  End of data  ****                                                
View             CSQ2:CSQ2.DEAD.QUEUE            +                 Top of 2    
Command ===>                                                       Scroll CSR  
      Col 289       Insert Length 4194304        Record AT TOP     Format HEX  
                                                                               
****** ****  Top of data  ****                                                
000001                                                                        
       4444444444444444444444444444                                            
       0000000000000000000000000000                                            
       -290--+----300--+----1----+-                                            
                                                                               
000002                                                                        
       4444444444444444444444444444                                            
       0000000000000000000000000000                                            
       -290--+----300--+----1----+-                                            
                                                                               
****** ****  End of data  ****

**Comment by ibmmqmet** [comment]
That is clearly showing the reason code in the DLH is 2035 (0x7F3) - MQRC_NOT_AUTHORIZED. Looks like the response to the command (which itself has also failed with 2035) cannot be put back to the TDQ.

The JES logs might show what RACF profiles are failing.

**Comment by garrotemar** [comment]
Hi Mark:
We found the problem, it was the same with the mcauser. I was arriving with the user mqm and in RACF said user did not exist. An existing mcauser was fixed in RACF and it worked correctly.

Thank you.
