### ISSUE TITLE
Depth based alert of a specific queue on Grafana

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-metric-samples#172]
We are sending the prometheus metrics to Grafana.
While we have an alert (see screenshot attached) that fires when a queue depth is high for any queue, is it possible to fire an alert on Grafana if I have (say) 1000 messages on a specific queue?
<img width="816" alt="Screenshot 2022-10-26 at 15 28 19" src="https://user-images.githubusercontent.com/33847625/198038484-6c8a0106-e7df-4b75-a39e-5eeaa7449699.png">

**Comment by ibmmqmet** [comment]
I'm not a Grafana expert, but my reading of the [alerting capabilities](https://grafana.com/docs/grafana/latest/alerting/fundamentals/alert-rules) suggests that you would need to have a query that matches the queue name you're interested in. 

So you create a query like `ibmmq_queue_depth{queue=~"APP.*"}` and then apply the criteria like the max depth. Which might be painful if you want to have 100 different queues with 100 different max values. But for just a couple of queues (or wildcard patterns) might be workable.

**Comment by abudavis** [comment]
We just have a few queues to set the maxdepth against. Do you know how and where to apply the maxdepth after the query?
