### ISSUE TITLE
amqzmuc0 process increases until system crashes

### ISSUE THREAD

**Issue by alvarocabanas** [ibm-messaging/mq-metric-samples#178]
Hello, we are using the version v5.3.2, specifically we are using the prometheus exporter. 

In a machine with monitoring an IBMMQ server with many monitored queues, we see the process amqzmuc0 increase over time until the system crashes, do you have any idea of why this could be happening? 

Could it be some connections not correctly closed by the exporter?

**Comment by ibmmqmet** [comment]
I've no idea what might cause that.  

What do you mean by "increase over time"? An apparent memory leak in the process? The single amqzmuc0 process holds things like the logger threads and has nothing to do with individual connections, though it does also generate metrics information that would be consumed by the collector programs.

And what do you mean by "the system crashes"? Are there any qmgr FDC files? 

From the tiny amount of information you've provided, I would suggest you might need to open a support ticket.

**Comment by alvarocabanas** [comment]
Hi @ibmmqmet, sorry to not be more specific, I mean the memory of that process increases progressively during 1 day span until it reaches the limit for that machine so the machine stops working.
Thanks for clarifying that the process doesn't have anything to do with connections, now we can skip that hypothesis of connections not being closed.
We are trying to investigate the issue that is happening only in one of our environments that we still didn't have the possibility to study further. Now that we will have access, we will be looking at the qmgr FDC files, as you suggest, before the machine stops. Do you have any other suggestion to take in consideration?

**Comment by paologallinaharbur** [comment]
Currently, if the exporter is enabled `amqzmuc0` starts consuming more and more memory, reaching 4-5 GB (and then stopping since the instance has no more memory available).

Once the exporter is disabled the memory increase stops completely and restarting the amqzmuc0 process it starts to consume again 25 MB.

Any idea how could we triage what is causing this leak in amqzmuc0 process?
