### ISSUE TITLE
Listener metrics available?

### ISSUE THREAD

**Issue by MrStefanGit** [ibm-messaging/mq-metric-samples#183]
Hi, I have deployed this MQ monitor inside a Docker container, in order to collect the metrics of a remote Windows deployment of IBM MQ in Prometheus. The goal is to create a method of monitoring the MQ inside Grafana. The problem I have is the lack of information about the metrics exported by this monitor.

The metrics i want to visualize are (The first name is as shown in the admin interface and the second from the metrics in Prometheus):
	- Overall channel status = ibmmq_channel_status_squash (OR) ibmmq_channel_status
	- Listener status
	- Queue Open input count = ibmmq_queue_input_handles
	- Queue Open output count = ibmmq_queue_output_handles
	- Current queue depth = ibmmq_queue_depth
	
I fount the corresponding metrics for Queue Open input count, Queue Open output count, Current queue depth by comparing the values in the admin interface with those in the metrics. I also found the channel status for every connection in the channel, but i can't find any metric for the listener status. Is it possible to view the listener status using this MQ monitor? Is there a documentation for all the metrics that this MQ monitor is capable of exporting?

**Comment by ibmmqmet** [comment]
V5.3.3 includes the `qmgr_active_listeners` counter

**Comment by MrStefanGit** [comment]
Thank you for your support!
