### ISSUE TITLE
hostname and description tags for qmgr

### ISSUE THREAD

**Issue by AntonioTrindade** [ibm-messaging/mq-metric-samples#184]
Greetings,

Is it possible to include the host name and the queue manager's description (DESCR field) as tags.
I have hundreds of queue managers and is would be a lot easier to select the queue manager by description instead of by name.

Also, I have found that, at least in the mq_influx collector, the host tag gets set to the destination InfluxDB hostname and not the queue manager's host name.

Thanks in advance.

**Comment by ibmmqmet** [comment]
Adding the qmgr description is reasonable, and I'll think about adding it for the next update.
Hostname is not currently feasible - if connecting as a client, the collector doesn't necessarily know where the qmgr is actually running. Especially in various HA environments where the qmgr might be active on one of several different systems. 

If the qmgr starts to report its own current hostname, then I would be able to report it.

The host reported by influx is not really anything directly reported here - it has to be an influx view of its own location.
