### ISSUE TITLE
Message are coming to system deadletter queue from Mq_exporter queue

### ISSUE THREAD

**Issue by Mathukumilli** [ibm-messaging/mq-metric-samples#19]
The messages are coming to system_dead_letter queue while it is creating a temp queue to fetch the metrics from IBM Mq by mq_exporter.

**Comment by ibmmqmet** [comment]
It's impossible to say what's going on here without a lot more information. For example: Platforms? What's the reason code on the DLQ? Are there any error log entries?

**Comment by Mathukumilli** [comment]
we have found two reasons:

1.MQRC_Q_DELETED
2.MQRC_Q_FULL

Where can we specify the maximum queue depth?
