### ISSUE TITLE
Config file as -f

### ISSUE THREAD

**Issue by lavalex** [ibm-messaging/mq-metric-samples#191]
Hello,

Is there an example of the config file that can be supplied to the executable, rather then setting all values as arguments?

Thank you in advance.

**Comment by ibmmqmet** [comment]
https://github.com/ibm-messaging/mq-metric-samples/blob/master/config.common.yaml + collector-specific additions in the subdirectories.

**Comment by lavalex** [comment]
Thank you .... I didn't realize THAT was the config file ....
