### ISSUE TITLE
Interval variable init in main.go of mq_aws

### ISSUE THREAD

**Issue by lavalex** [ibm-messaging/mq-metric-samples#192]
Hello,

I think there is a type in main.go of mq_aws in line 49:

		d, err := time.ParseDuration(interval)

Which from what I understand, creates a local variable and then "d" goes back to zero, so the loop never "sleeps".

Should be:

               d, err = time.ParseDuration(interval)

**Comment by ibmmqmet** [comment]
Yes you are right. I'll fix it for the next release. Thanks for finding it.
