### ISSUE TITLE
Prometheus IBM MQ metrics for total queue count 

### ISSUE THREAD

**Issue by maggimedha** [ibm-messaging/mq-metric-samples#199]
Please include the following information in your ticket.
Hi,

We are trying to get total IBM MQ messages count report in Queue manager using Prometheus and grafana monitoring. Could you please help us to get grafana metric for messages total count.

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.

**Comment by ibmmqmet** [comment]
Look at the sample grafana dashboards provided in this repo. The "MQ Prometheus" dashboard has a panel called "Messages". You can review the metrics used by the queries for that panel.
