### ISSUE TITLE
Incorrect link to MQ KnowledgeCenter in README.md

### ISSUE THREAD

**Issue by postum** [ibm-messaging/mq-metric-samples#201]
file https://github.com/ibm-messaging/mq-metric-samples/blob/master/cmd/mq_prometheus/README.md

has an incorrect link to [MQ KnowledgeCenter](https://www.ibm.com/support/knowledgecenter/SSFKSJ_latest/com.ibm.mq.mon.doc/mo00013_.htm)   this link gives "We're sorry! Content not found" now, 
Is it possible to find this article with a new, correct, link? Or to find a snapshot/copy of original article?

**Comment by ibmmqmet** [comment]
Thanks for finding that. The new docs link should be https://www.ibm.com/docs/en/ibm-mq/latest?topic=trace-metrics-published-system-topics 

I'll fix it on the next update.
