### ISSUE TITLE
MQ Metric Samples does not support s390x

### ISSUE THREAD

**Issue by Joshua-Beha** [ibm-messaging/mq-metric-samples#209]
- mq-metrics-samples version(s): All
 
I am attempting to build the mq-metric-samples Dockerfile within OCP on Z with the goal of collecting queue level metrics for queues created with the IBM MQ Operator. Attempting to build the Dockerfile works fine until `RUN go build -mod=vendor -o /go/bin/${EXPORTER} ./*.go` when MQ libraries cannot be imported because they are incompatible. This makes sense because the [`9.3.2.0-IBM-MQC-Redist-LinuxX64.tar.gz`](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/9.3.2.0-IBM-MQC-Redist-LinuxX64.tar.gz) redistributable client is only for x86-64. Changing the `MQARCH` environment variable would not help because only x86 redistributable clients are available at the [given URL](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/). Could s390x redistributable clients or a s390x compatible Dockerfile be made available?

**Comment by Joshua-Beha** [comment]
I still think adding s390x support would be beneficial but I was able to get a temporary solution (posting here in case anyone comes across this). 

By editing the Dockerfile I can build the mq-metric-samples image. I needed to get the `9.2.0.10-IBM-MQC-UbuntuLinuxS390X ` package from [here](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&product=ibm/WebSphere/WebSphere+MQ&release=9.2.0.0&platform=Linux+64-bit,zSeries&function=all), untar, navigate to the new MQClient directory then install with `apt install ibmmq-runtime_<version>_s390x.deb && apt install ibmmq-sdk_<version>_s390x.deb`.

**Comment by ibmmqmet** [comment]
Dealing with a set of "real" installation can be tricky in the general case. (Just see the `mq-container` repository for examples of what you have to do.) But I think I can modify the current basic `Dockerfile` in a relatively clean way with some assumptions. 

For example, it will be `.deb` files only as that Dockerfile uses an Ubuntu base. You must obtain the image yourself and then copy files into a specific directory of the repo. I don't want to complicate things or proliferate build scripts/Dockerfiles too much. And these are meant as samples, so some customisation is expected.

I'll look to publish something in the next update.

**Comment by ibmmqmet** [comment]
You can do this now via the Dockerfile build process provided you have the deb files available in an MQINST directory
