### ISSUE TITLE
mq_prometheus - lack of MQPUT / MQGET metrics for UNIX platform

### ISSUE THREAD

**Issue by rpysz** [ibm-messaging/mq-metric-samples#213]
Currently, mq_prometheus does not expose metrics regarding MQPUT or MQGET values for individual queues if the platform on which IBM MQ runs is UNIX. According to the source code, such two basic metrics are only available for the Z/OS platform. 

It would be useful if the exporter made more metrics available for MQPUT and MQGET, as is currently available, for example, in the mq-java-exporter project:
https://github.com/Cinimex/mq-java-exporter#mqget-metrics-1
https://github.com/Cinimex/mq-java-exporter#mqput-metrics

**Comment by ibmmqmet** [comment]
What makes you think it's not there already? For example `ibmmq_queue_mqget_count`. The values for z/OS are explicitly extracted from the RESET QSTATS command. For other platforms, it's done via the published metrics.

**Comment by rpysz** [comment]
@ibmmqmet Thank you for directing me to the solution. It turned out that my default configuration had the 'usePublications' parameter set to 'false'.
