### ISSUE TITLE
Topic Metric Exporting

### ISSUE THREAD

**Issue by r-ushil** [ibm-messaging/mq-metric-samples#218]
Hi there,

I'm using the latest version of mq-metric-samples. I have successfully connected it up to an MQ instance and I am seeing queue specific metrics fine, but cannot see topic specific metrics. I have added the following section in my YAML config, under objects.

 topics:
    - "APPLICATION.*"
    
Any advice would be appreciated!

**Comment by ibmmqmet** [comment]
Topics usually use "#" as the wildcard

**Comment by r-ushil** [comment]
Hi Mark, thanks for the quick response. I can see topic in MQ explorer, but when my topics section is just the following, I can't see any ibmmq_topic* metrics.

topics:
- "#"

Is this a config problem, or does MQ exporter not support topic specific metrics?

Thanks!
