### ISSUE TITLE
No more ibmmq_queue_depth metrics after upgrade to MQ 9.3.0.4

### ISSUE THREAD

**Issue by fnuzzi** [ibm-messaging/mq-metric-samples#219]
After upgrade to MQ LTS v. 9.3.0.4 from MQ v. 9.2.0.4, the prometheus exporter does not report anymore the ibmmq_queue_depth metrics.
We have updated multiple machines in our test and production environment and all of them have stopped reporting qdepth metrics immediately after the upgrade. 
I am running the latest MQ Prometheus exporter v. 5.4.0. The mq_prometheus binary reports no error in its log file at startup.
Is there anything we can check or do to try identify what the problem might be? Those metrics are key to alert generation

**Comment by fnuzzi** [comment]
I have set log level to debug and restarted the mq_exporter. At the beginning there is a series of 'Created gauge for' messages but  there is indeed no gauge created for "queue_depth". So metric seems really missing.

**Comment by ibmmqmet** [comment]
You don't show your configuration so I can only guess that the `filters.queueSubscriptionSelector` option doesn't include `General`. The queue depth was moved to a different class of metric at some point during 9.2 development. 

You can confirm that by using the amqsrua sample against the old and new versions of MQ. And the debug output from the collector might also show something like "Not subscribing to Class STATQ Type GENERAL resources"

**Comment by fnuzzi** [comment]
Thanks a lot Mark.
Indeed my filter.queueSubscriptionSelector was set to PUT and GET. I have also added GENERAL and now qdepth metrics are back.

**Comment by fnuzzi** [comment]
I missed the info about queue depth being moved to a different class of metric at some point during 9.2 development.
