### ISSUE TITLE
Is there a binary version available？

### ISSUE THREAD

**Issue by shinehertheway** [ibm-messaging/mq-metric-samples#22]
What I saw on github, I don't know how to integrate it into a complete monitoring plugin. Although you gave some introductions, there is no binary integrated version provided.

**Comment by ibmmqmet** [comment]
There is a script in the root of this repository to make it very simple to build the monitor programs in a Docker container. The README shows how to use it. Binaries are not supplied here.

**Comment by shinehertheway** [comment]
I'm not going to use the Docker container, so is there a way to start directly by executing scripts without using the Docker container?

**Comment by ibmmqmet** [comment]
There are full instructions in the various README files in the repository for how to compile the source into binaries. 

The buildInDocker.sh script could of course be used locally too, outside a container, provided you manually set the relevant environment variables that are set in bye Dockerfile.

There are too many variations of what people might have installed, where, on different distributions, to provide a single simple standalone script. All of the differences can be controlled when using Docker but if you want to run in your own environment, you have to manage that variation.

There are sample startup scripts included that will execute the binaries, but you have to do the compilation first.

**Comment by shinehertheway** [comment]
Thank you. I'm taking a closer look.

**Comment by shinehertheway** [comment]
The following error occurs when I execute the build command.I don't know where to report it, so I'm looking for your guild leader.
The command:go build -o bin/mq_prometheus src/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/*.go
The error:# command-line-arguments
src/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/main.go:53:71: cannot use &config.cf.CC (type *"github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric".ConnectionConfig) as type *"ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric".ConnectionConfig in argument to "ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric".InitConnection

**Comment by ibmmqmet** [comment]
answered
