### ISSUE TITLE
Persistent message count per queue

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-metric-samples#220]
Thank you for making the mq-metrics-samples available, it has really been useful for us! 
We use the metric samples on our CP4I deployment along with Grafana dashboard.
We however have a feedback.

Just like the metric "ibmmq_qmgr_persistent_message_mqput_count" which would show us the number of persistent messages PUT to the entire queue manager, it would really be more useful if we could see this per queue. Is this something that can be made available as part of a future release?

**Comment by ibmmqmet** [comment]
How about using the already available `ibmmq_queue_mqput_persistent_message_count` (and the PUT1 equivalent)

**Comment by abudavis** [comment]
Thats perfect, thank you!
-What is really the difference between PUT and PUT1?
-I really wonder why the queue & channel metrics are missing on the cloud pak? - https://www.ibm.com/docs/en/ibm-mq/9.3?topic=operator-metrics-published-when-using-mq

**Comment by ibmmqmet** [comment]
See the [programming docs](https://www.ibm.com/docs/en/ibm-mq/9.3?topic=queue-putting-one-message-using-mqput1-call) for the difference between MQPUT and MQPUT1 verbs.

The cloudpak inbuilt metric collector does not use current versions of this package (it's actually based off the very first release) , and therefore has many limitations in comparison.
