### ISSUE TITLE
ibmmq_qmgr_mqput_mqput1_total metric missing

### ISSUE THREAD

**Issue by wardniall** [ibm-messaging/mq-metric-samples#228]
Hi

We're looking to resurrect some old grafana dashboards to display metrics about our MQ. They're quite old so I suspect they are now out of date. Some of our graphs are blank as a consequence of the ibmmq metrics not being available in Prometheus. A prime example is ibmmq_qmgr_mqput_mqput1_total. Is it possible that this metric is no longer being surfaced by the mq_exporter and is instead called something else? metrics.txt on this repo would indicate that mqput_mqput1_total is not available under the qmgr class, but perhaps I am interpreting it incorrectly.

**Comment by ibmmqmet** [comment]
That metric name does look out of date. There have been some reworks over time either from the qmgr side, or in the heuristics used to convert names into a more prometheus-friendly format.

The metrics.txt file says that it explictly lists only those metrics that are NOT provided from the topic-provided resource metrics already shown in the full product documentation. If you follow that link to the docs, you'd find "Interval total MQPUT/MQPUT1 count X" as one of the metrics. Which would get converted to `ibmmq_qmgr_interval_mqput_mqput1_total_count`. One easy way to find the metric names is to stop prometheus from actually calling the collector, and then do
`curl -Ss <hostname>:9157/metrics | grep "^ibmmq"`

**Comment by wardniall** [comment]
Thanks for the prompt reply, apologies for my own tardiness. One of my children had a medical emergency which has taken my attention for the last few days. Unfortunately I don't see the ibmmq_qmgr_interval_mqput_mqput1_total_count metric in my output, the only ibmmq related metrics I see are:

ibmmq_qmgr_active_listeners gauge
ibmmq_qmgr_channel_initiator_status gauge
ibmmq_qmgr_command_server_status gauge
ibmmq_qmgr_connection_count gauge
 ibmmq_qmgr_exporter_publications gauge
 ibmmq_qmgr_log_extent_archive gauge
 ibmmq_qmgr_log_extent_current gauge
 ibmmq_qmgr_log_extent_media gauge
 ibmmq_qmgr_log_extent_restart gauge
 ibmmq_qmgr_log_size_archive gauge
 ibmmq_qmgr_log_size_media gauge
 ibmmq_qmgr_log_size_restart gauge
 ibmmq_qmgr_log_size_reusable gauge
 ibmmq_qmgr_status gauge
 ibmmq_qmgr_uptime gauge
 ibmmq_queue_attribute_max_depth gauge
 ibmmq_queue_attribute_usage gauge
 ibmmq_queue_depth gauge
 ibmmq_queue_input_handles gauge
 ibmmq_queue_oldest_message_age gauge
 ibmmq_queue_output_handles gauge
 ibmmq_queue_qfile_current_size gauge
 ibmmq_queue_qfile_max_size gauge
 ibmmq_queue_qtime_long gauge
 ibmmq_queue_qtime_short gauge
 ibmmq_queue_time_since_get gauge
 ibmmq_queue_time_since_put gauge
 ibmmq_queue_uncommitted_messages gauge

Given that the only config I can see being pushed to our container is

**Comment by ibmmqmet** [comment]
`usePublications` should be `true`

**Comment by wardniall** [comment]
Thanks, that did the trick. I can now see all the metrics with the names described in your comment above. Closing this ticket, thanks for your assistance.
