### ISSUE TITLE
Build Test Container

### ISSUE THREAD

**Issue by gabrielnewrelic** [ibm-messaging/mq-metric-samples#23]
I am building the ibm-messaging/mq-container from the Dockerfile and i can specify the enable prometheus metrics, but all i get is the qmgr metrics and I am not even sure if that is accomplished with the mq-metric-samples. 
Do we have a sample mq container that has all the prometheus metrics enabled (queues, channels, etc)? OR is there any easy way to build the ibm-messaging/mq-container with the latest version of mq-metric-samples?

**Comment by ibmmqmet** [comment]
The mq-container does not use this repository, although its monitoring component was derived from  an earlier version of this code. The monitoring capability in that package was only enabled for queue manager resources.

There's no sample container provided that has this included, but there is the buildMonitors script in the root of this repository to enable building a container and the binaries. With some simple modifications to that script and associated Dockerfile you ought to be able to use the mq-container image as a base, and then add the full prometheus monitoring component.

**Comment by ibmmqmet** [comment]
answered
