### ISSUE TITLE
Precompiled ibmmq_exporter

### ISSUE THREAD

**Issue by tqivbatista** [ibm-messaging/mq-metric-samples#235]
Is there a possibility to create a pipeline to generate and make available the precompiled **ibmmq_exporter** binary for the main architectures ?

I see that most exporters do this and it saves the user a lot of time.

**Comment by ibmmqmet** [comment]
I've got no plans to add precompiled binaries or container images. 

The `Dockerfile`  and the various build scripts should make it very easy for people to create their own images for a variety of plaform configurations and deployment approaches including standalone programs that might then be layered into containers holding the full MQ code, or for building single-purpose containers. 

You can then add your preferred model to your own pipeline based on those files/scripts.
