### ISSUE TITLE
IBM mq volume metrics based on queue manager and queue

### ISSUE THREAD

**Issue by laxmi1219** [ibm-messaging/mq-metric-samples#236]
Hi mark,

Grafan dashbook looks great and it's very useful. If possible can you plz add the dashboard panel to get the volume metrics total number of put and get volume based on queue and queue manager. It will more helpful.

**Comment by ibmmqmet** [comment]
The dashboards provided in this repository are intended as samples to show the kinds of metrics that can be extracted and as demonstrations on how to create the queries. They are not meant as "production-quality" dashboards to use unchanged. 

You neeed to build on the examples using the documentation on which metrics are available, and then create your own dashboards showing what you find valuable.
