### ISSUE TITLE
I need monitor two queueManagers.

### ISSUE THREAD

**Issue by tqivbatista** [ibm-messaging/mq-metric-samples#239]
Can you help me to config this yaml. 

```
connection:
  queueManagers:
  - QM.X
  - QM.Y
```

**Comment by ibmmqmet** [comment]
The collectors only work with a single queue manager. So you need two separate collector instances, each with its own configuration file.

**Comment by s-mesh** [comment]
I need to monitor two queue Managers on the same Prometheus instance.
But getting below errors for one of the QMgrs

Failed to handle metrics request: listen tcp :9157: bind: address already in use"
Must provide a queue manager name to connect to."

**Comment by ibmmqmet** [comment]
So you set up two collectors each with their own port number in their own configuration files - perhaps 9157 and 9158 . That's why the prometheus.port is a config parameter.
