### ISSUE TITLE
Where is the queue manager name configured? Is it auto lookup or profile?

### ISSUE THREAD

**Issue by shinehertheway** [ibm-messaging/mq-metric-samples#24]
Where is the queue manager name configured? Is it auto lookup or profile?
I successfully built the project, because the package path of import seems to have changed, so I changed the package path of import, but nothing else was changed, and then the following errors were included during startup：
IBM MQ metrics exporter for Prometheus monitoring

ERRO[0000] Must provide a queue manager name to connect to.

**Comment by ibmmqmet** [comment]
Look at the startup script - mq_prometheus.sh to see how parameters can be supplied. Or run the binary with the usual -help flag.

**Comment by ibmmqmet** [comment]
answered
