### ISSUE TITLE
Queue Level Metrics not visible on Prometheus dashboard

### ISSUE THREAD

**Issue by SAshish19** [ibm-messaging/mq-metric-samples#243]
I am starting the metric collection application in a docker container however its giving only Queue Manager level metric. Metric for queues like ibmmq_queue_depth are not visible on Promethus. Do we need to enable/pass any other attribute as well for queue metrics to be available on Prometheus dashboard ? 

docker run --rm -p 9157:9157 \
              -e IBMMQ_CONNECTION_QUEUEMANAGER="QM1" \
              -e IBMMQ_CONNECTION_CONNNAME="<IP address>(1414)" \
              -e IBMMQ_CONNECTION_CHANNEL="SYSTEM.DEF.SVRCONN" \
              -e IBMMQ_GLOBAL_CONFIGURATIONFILE="" \
              -e IBMMQ_OBJECTS_QUEUES="*" \
              -it mqprom:1.0

**Comment by ibmmqmet** [comment]
If you run the program with debug level logging you will see the full applied configuration options. . Look at the `config.common.yaml` file for all the common options with reasonable defaults.

You're probably missing the `usePublications` setting.

**Comment by SAshish19** [comment]
Thanks a lot for the help. I was able to resolve it.
