### ISSUE TITLE
Listener metrics

### ISSUE THREAD

**Issue by SandyIrvin** [ibm-messaging/mq-metric-samples#244]
I am running IBM MQ 9.3.x on Linux system and trying to capture metrics and create Dashboards on grafana. I have followed steps, compiled the code and deployed to queue manager as a service. However when i see the metrics getting exported, i dont see anything associated with listener at all.

Here is how i am invoking the code using a shell script.

exec mq_prometheus -ibmmq.queueManager=\$qMgr -ibmmq.httpListenPort=\$port -ibmmq.monitoredQueues=* -ibmmq.monitoredChannels=* -ibmmq.showInactiveChannels=true -ibmmq.monitoredTopics=# -ibmmq.monitoredSubscriptions=* -rediscoverInterval=1h -ibmmq.useStatus=true -log.level=error

**Comment by ibmmqmet** [comment]
What metrics are you expecting? The only one reported is `qmgr_active_listeners`. And that requires the `useObjectStatus` option (or `UseStatus` when setting on the command line) to be enabled.

**Comment by SandyIrvin** [comment]
So you mean i need to add this as an additional argument while invoking other objects some thing like below?

exec mq_prometheus -ibmmq.queueManager=$qMgr -ibmmq.httpListenPort=$port -ibmmq.monitoredQueues=* -ibmmq.monitoredChannels=* -ibmmq.showInactiveChannels=true -ibmmq.monitoredTopics=# -ibmmq.monitoredSubscriptions=* -rediscoverInterval=1h -ibmmq.useStatus=true -log.level=error -ibmmq.useObjectStatus=true

**Comment by ibmmqmet** [comment]
And are you not seeing the `qmgr_active_listeners` metric? Are you expecting something else?
