### ISSUE TITLE
panic: inconsistent label cardinality: expected 4 label values but got 3 in prometheus.Labels

### ISSUE THREAD

**Issue by Ronmck** [ibm-messaging/mq-metric-samples#245]
I was testing stopping my queue manager while the mq_prometheus  was running
I am running MQ ver 9.3.2
This is a extract from my yaml file.
 
prometheus:
  port: 9150
  metricsPath: "/metrics"
  namespace: ibmmq
# Keep running even if the qmgr is not available - allows a "STOPPED" status to be
# returned to the Prometheus server.
  keepRunning: true
# How often to check the status and to attempt to reconnect if there's been a failure
  reconnectInterval: 30s

mq_prometheus  sucessfully runs and then when I stop my queue manager the connector fails after trying to reconnect.

IBM MQ metrics exporter for Prometheus monitoring
MQ Go Version : v5.5.0

INFO[0000] Trying to connect as client using ConnName: localhost(54000), Channel: MQMETRICS.CHL
INFO[0000] Connected to queue manager GWDV01
INFO[0000] IBMMQ Describe started
INFO[0000] Platform is UNIX
INFO[0000] Listening on http address :9150
ERRO[0137] Error processing publications: MQGET: MQCC = MQCC_FAILED [2] MQRC = MQRC_CONNECTION_BROKEN [2009]
INFO[0150] Trying to connect as client using ConnName: localhost(54000), Channel: MQMETRICS.CHL
INFO[0180] Trying to connect as client using ConnName: localhost(54000), Channel: MQMETRICS.CHL
INFO[0210] Trying to connect as client using ConnName: localhost(54000), Channel: MQMETRICS.CHL
INFO[0240] Reporting status as disconnected
panic: inconsistent label cardinality: expected 4 label values but got 3 in prometheus.Labels{"description":"Dev Gateway API Testing", "platform":"UNIX", "qmgr":"GWDV01"}

goroutine 15 [running]:
github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(...)
        /opt/mqrepo/mqmetrics/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_golang/prometheus/gauge.go:250
main.(*exporter).Collect(0xc0002c7e00, 0xc0004c0240)
        /opt/mqrepo/mqmetrics/src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/exporter.go:182 +0x47f
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /opt/mqrepo/mqmetrics/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_golang/prometheus/registry.go:455 +0x10d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /opt/mqrepo/mqmetrics/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/prometheus/client_golang/prometheus/registry.go:466 +0x59d

**Comment by ibmmqmet** [comment]
Thanks for the report.I was able to reproduce and It looks like the collector "forgets" the relevant state info after a disconnect flow. 

I have a fix that I will include in the next release. As a temporary workround, you can change the function `supportsHostnameLabel` in `exporter.go` to always return `true`.

**Comment by Ronmck** [comment]
Thanks Mark using your workaround
