### ISSUE TITLE
Queue manager must be at least V9.0

### ISSUE THREAD

**Issue by guojing1983** [ibm-messaging/mq-metric-samples#247]
When I am using the IBM MQ metrics exporter for Prometheus version 5.5.0 to connect to the queue manager of IBM MQ version 8.0.0.4, I am prompted with 'Connection to QM_10 has failed. Unsupported system: Queue manager must be at least V9.0 for full monitoring.'. If I want to monitor which version of IBM MQ metrics exporter for Prometheus should be used for IBM MQ 8.0.0.4
![image](https://github.com/ibm-messaging/mq-metric-samples/assets/60596094/b0998fd6-e923-442c-9449-07d8f7aeb53a)
![image](https://github.com/ibm-messaging/mq-metric-samples/assets/60596094/4999c6c4-4641-45e6-aa6a-f66fea1b6169)

**Comment by ibmmqmet** [comment]
The package does work against a V8 qmgr provided, as the message says, you use the collector's configuration opitions to disable the attempt to use the resource publications. 

But it then will be very limited in the metrics it can provide. And MQ V8 itself is a long way out of support (your version was shipped in 2015 according to the dspmqver output)..
