### ISSUE TITLE
Prometheus Remote Write Support 

### ISSUE THREAD

**Issue by Ronmck** [ibm-messaging/mq-metric-samples#251]
Are there any plans to support Prometheus remote write 
https://prometheus.io/docs/concepts/remote_write_spec/

**Comment by ibmmqmet** [comment]
No plans. It appears sufficiently different that it doesn't fit at all in the current Prometheus client libraries, but would need to be a completely different exporter module. Something more like the InfluxDB exporter perhaps. What would be the use case here, that couldn't be handled using the Prometheus server's remote write capability?

**Comment by Ronmck** [comment]
Thanks Mark, just realized that I can configure Prometheus  Server for remote write, we have instance of Grafana Mimir can be the receiver, this will allow  horizontally scalable, highly available, multi-tenant, long-term storage for Prometheus
