### ISSUE TITLE
Not able to get info for shared queues

### ISSUE THREAD

**Issue by SigurjonMagnusson** [ibm-messaging/mq-metric-samples#26]
name = "github.com/ibm-messaging/mq-golang"
  version = "4.1.0"

Using MQ client;  MQSeriesRuntime-9.0.0-7.x86_64.rpm
Connecting to IBM MQ for z/OS ver v9.0.0.0

Able to get info when QSG disposition = 'Queue manager' but not when 'Shared'.  Is this not available with client?

**Comment by ibmmqmet** [comment]
The version I've just pushed should be able to work with shared queues. 

There seems to be an annoying difference in defaults between the PCF and MQSC commands as to whether shared queues are returned in certain outputs. So now they are explicitly asked for.

**Comment by SigurjonMagnusson** [comment]
Awesome. This is now working with shared queues :)
