### ISSUE TITLE
mq_prometheus: allow enable/disable status metrics separately

### ISSUE THREAD

**Issue by sigilioso** [ibm-messaging/mq-metric-samples#263]
We are using the `mq_prometheus` exporter and we would like to enable or disable the collection of different status separately.

Using the [ibmmq.useStatus](https://github.com/ibm-messaging/mq-metric-samples/blob/e0456b1f8639121e5fdf3eb22c404c224f96777c/pkg/config/config.go#L190) option it is possible to enable/disable the collection of metrics from all object STATUS fields. However, we would like to do this separately. For instance, we would like to be able to keep Queue status, but disable the collection of Channel and Topic status:

I guess we would need to modify the [exporter](https://github.com/ibm-messaging/mq-metric-samples/blob/e0456b1f8639121e5fdf3eb22c404c224f96777c/cmd/mq_prometheus/exporter.go#L278) to check additional configuration fields:

```go
				// check ChannelStatus configuration flag here
				if err == nil {
					err := mqmetric.CollectChannelStatus(config.cf.MonitoredChannels)
					if err != nil {
						log.Errorf("Error collecting channel status: %v", err)
						pollError = err
					} else {
						log.Debugf("Collected all channel status")
					}
				}
				// check TopicStatus configuration flag here
				if err == nil {
					err = mqmetric.CollectTopicStatus(config.cf.MonitoredTopics)
					if err != nil {
						log.Errorf("Error collecting topic status: %v", err)
						pollError = err
					} else {
						log.Debugf("Collected all topic status")
					}
				}
				// check SubStatus configuration flag here
				if err == nil {
					err = mqmetric.CollectSubStatus(config.cf.MonitoredSubscriptions)
					if err != nil {
						log.Errorf("Error collecting subscription status: %v", err)
						pollError = err
					} else {
						log.Debugf("Collected all subscription status")
					}
				}
				// check QueueStatus configuration flag here
				if err == nil {
					err = mqmetric.CollectQueueStatus(config.cf.MonitoredQueues)
					if err != nil {
						log.Errorf("Error collecting queue status: %v", err)
						pollError = err
					} else {
						log.Debugf("Collected all queue status")
					}
				}

```

I am aware we could use filters, but we would like to avoid polling resources when metrics are not needed.

If this use case makes sense to you and you could provide some guidance, we would be happy to contribute to get it implemented.

**Comment by ibmmqmet** [comment]
If you don't set any object patterns, then no status queries should actually be made for that object type. eg
```
objects:
   channels:
   topics:
```
Functions like CollectChannelStatus would simply return immediately.

**Comment by sigilioso** [comment]
Thanks for pointing that out @ibmmqmet,

I think I got it wrong because the [patterns are checked](https://github.com/ibm-messaging/mq-metric-samples/blob/e0456b1f8639121e5fdf3eb22c404c224f96777c/vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go#L220) after initializing everything else to perform status queries. 

Would it make sense to move the check to the beginning of those functions?

**Comment by ibmmqmet** [comment]
I don't think so.

Most of the code "above" the checking of the patterns makes sure we've got a clean response back to the main functions. While none of the current collectors do it, I can certainly imagine collectors that dynamically change the list of objects, and would rely on having that cleanup processing done between each iteration.

**Comment by sigilioso** [comment]
Thanks for the explanation.
