### ISSUE TITLE
MQ certified container reference

### ISSUE THREAD

**Issue by vgavinash** [ibm-messaging/mq-metric-samples#264]
@ibmmqmet Hi Mark, the file `cp4i/README.md` under mq-metric-samples project has a mention of `MQ certified container`. This needs to be changed to `MQ container`. Could you please update? 

Cc: @arthurbarr

**Comment by ibmmqmet** [comment]
ok. I'll do that for whenever the next update goes out

**Comment by vgavinash** [comment]
Thanks! :-)
