### ISSUE TITLE
Problems compiling mq_influx

### ISSUE THREAD

**Issue by bertoc1975** [ibm-messaging/mq-metric-samples#27]
Hi,

I'm having problems trying to get a compiled version of mq_influx. I'm using
go version go1.13.6 linux/amd64

I've tried multiple things but I'm stucked in this error:
# go build -o bin/mq_influx src/ibm-messaging/mq-metric-samples/cmd/mq_influx/*.go
# command-line-arguments
src/ibm-messaging/mq-metric-samples/cmd/mq_influx/main.go:54:70: cannot use &config.cf.CC (type *"github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric".ConnectionConfig) as type *"ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric".ConnectionConfig in argument to "ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric".InitConnection

Is it related to the go version I'm using? Or it's something else I'm missing? I've followed the related README files.

Regards.

**Comment by ibmmqmet** [comment]
I suspect the README is slightly out of date with regard to the file path into which you clone the repo. A working tree should now look something like `$GOPATH/src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_influx` (note the extra github.com). I think that's what's causing the mismatched datatype in your build.

The `buildMonitors.sh` script at the repo root can be used to create working paths and then build in a Docker container which may be more convenient.

I'll take a look at the various READMEs and try to update/consolidate the instructions as there seems to be a lot of mostly-duplicated info across them for historic reasons.

**Comment by ibmmqmet** [comment]
The READMEs and `buildMonitors.sh` script have recently been restructured and updated to take account of the latest version which uses Go modules.
