### ISSUE TITLE
Invalid tag does not allow compilation of monitors

### ISSUE THREAD

**Issue by kang-makes** [ibm-messaging/mq-metric-samples#277]
There is an invalid tag n this repository that does not allow build any monitors.

The tag is this one: https://github.com/ibm-messaging/mq-metric-samples/releases/tag/v5.5.%60

## Steps for reproduction
`git reset --hard master`
```
HEAD is now at d389b8d Fix to Dockerfile to cope with buildah differences
```
`cd scripts`
`./buildMonitors.sh`
```
Building container mq-metric-samples-gobuild:5.5.`
[+] Building 0.5s (1/1) FINISHED                                                                                             docker-container:desktop-linux
 => [internal] booting buildkit                                                                                                                        0.4s
 => => starting container buildx_buildkit_desktop-linux0                                                                                               0.4s
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
ERROR: invalid tag "mq-metric-samples-gobuild:5.5.`": invalid reference format
```

The issue points to this line of script: https://github.com/ibm-messaging/mq-metric-samples/blob/d389b8d3c5f7277c19c58ad351f537c2bd6298d4/scripts/buildMonitors.sh#L32

Because of how `VER` is parsed: https://github.com/ibm-messaging/mq-metric-samples/blob/d389b8d3c5f7277c19c58ad351f537c2bd6298d4/scripts/common.sh#L3-L28

A simple "git push --delete origin v5.5.`" should do the trick.

**Comment by ibmmqmet** [comment]
I've removed the weird tag. Should be OK now. It's been in there for a while, so the most recent push shouldn't have affected it. 

I am wondering whether your "sort" command is using a different collation sequence to mine, as I wasn't seeing any errors. The odd tag wasn't at the end of my sorted list, so when I build, it wasn't being used.
