### ISSUE TITLE
How to collect additional MQ metrics?

### ISSUE THREAD

**Issue by SenthilRagu** [ibm-messaging/mq-metric-samples#278]
Affected version: v5.5.0

Thanks for building and sharing the Prometheus monitoring for MQ. 
Im new to this and just did the setup as mentioned in the doc and able to see MQ stats.
However I have some questions regarding the stats that are getting collected.

We are running MQ9.3 on Openshift containers and we are able see all the metrics as mentioned in this doc - https://github.com/ibm-messaging/mq-metric-samples/blob/master/metrics.txt

Question-
If any additional metrics needs to be collected is there a way that we can modify config or code to get the stats?

For ex-
How to collect the SSL CIPHER and Remote Client version in Channel status? 
in MQ, Remote application Cipher and version is in the display command output, but this metrics is not collected by Prometheus. 

dis chs(TEST.CHL) ALL
SSLCIPH( )
RVERSION(09030011)

**Comment by ibmmqmet** [comment]
The examples you give are not metrics. They are status values. And they are strings, not numbers. 

While it would be technically possible to collect them, they could only be available via labels, not as metrics that show up on graphs. The values do not change through the lifetime of a channel instance.

It is not a good idea to have lots of labels on data points. We try to collect the minimum set of attribute and status values to use as labels, the ones that are really essential to identify the object.
