### ISSUE TITLE
Howto monitor multiple queue managers with 1 instance of mq_prometheus

### ISSUE THREAD

**Issue by kidharb** [ibm-messaging/mq-metric-samples#30]
Please include the following information in your ticket.

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.

Instead of running multiple instances of mq_prometheus, is there a way to aggregate the data from multiple queue managers and have them all exported to a single <server>:9157/metrics webpage?

**Comment by ibmmqmet** [comment]
Not possible with this code. It assumes only working with a single queue manager
