### ISSUE TITLE
How to set TZ Offset value in the program configuration

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-metric-samples#314]
We are using the latest mq-metrics-sample (v5.6.0) that is compiled to extract metrics from an MQ QMGR on v9.3 running on a RHEL v8 VM. We send the prometheus metrics to Grafana SaaS Cloud instance from metrics pod setup on Openshift.

On Grafana, we have a dashboard with a panel configured with query:  last_over_time(ibmmq_queue_time_since_get[$__range])

The issue is that the metrics pod on Openshift is naturally on UTC, whereas the MQ server is on CEST timezone. I tried to set the metrics pod to an environment variable 'TZ' to 'CET-1CEST,M3.5.0/2,M10.5.0/3', but this only changed the date (command) inside the metrics pod but it kept giving this error, how can we fix this? How do we set the TZ Offset value in the program configuration?

```
IBM MQ metrics exporter for Prometheus monitoring
Build : 20220412-112013
Commit Level : d84f842
Build Platform: Linux/x86_64
time="2024-07-01T08:26:47Z" level=error msg="Status reports appear to be from the future. Difference is approximately 7199 seconds. Check the TZ Offset value in the program configuration
--
time="2024-07-01T08:25:51Z" level=info msg="Connected to queue manager QMGR15"
time="2024-07-01T08:25:53Z" level=info msg="IBMMQ Describe started"
time="2024-07-01T08:25:53Z" level=info msg="Platform is UNIX"
time="2024-07-01T08:25:53Z" level=info msg="Listening on http address :9157"

```

**Comment by ibmmqmet** [comment]
Look at the `global.tzOffset` config parameter

**Comment by abudavis** [comment]
> Look at the `global.tzOffset` config parameter

So that for cp4i/containers would include this?:
`oc create configmap metrics-configuration  --from-literal=IBMMQ_GLOBAL_TZOFFSET=7199` 

To what value should I set it to, the 7199 seconds reported in the logs or? Our QMGR is on Europe/Frankfurt TZ while Openshift metric pod is on UTC. How do we also ensure this is automatically adjusted in DST cutovers?

**Comment by abudavis** [comment]
@ibmmqmet Would it work if I add the docker instruction [ENV TZ='Europe/Oslo'] or [ENV TZ='CET-1CEST,M3.5.0/2,M10.5.0/3'] to here? https://github.com/ibm-messaging/mq-metric-samples/blob/master/Dockerfile.run

**Comment by abudavis** [comment]
@ibmmqmet I am running the collector/metrics as a pod and the OS seems to be the one shown below, setting the TZ as an environment on the Openshift deployment (similar to your docker command I guess) did change the time on the pod terminal but the metrics pod still reported the time difference, so this clearly does not work. Any other suggestions? We want something that will continue to work with DST cutovers so that we dont have to manually change the IBMMQ_GLOBAL_TZOFFSET/global.tzOffset twice a year.

```
$ uname -a
Linux mq-metric-qmgr1-578cdc95d8-wjjwg 5.14.0-284.82.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 22 12:25:01 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alexisph** [comment]
What worked for me on OpenShift was setting the TZ envvar and in addition mounting the correct timezone data file over /etc/localtime

**Comment by abudavis** [comment]
@alexisph What is the base docker image you used to deploy the MQ client + metric sample? Coz the one I am using does not have a zone file, the /etc/localtime must point to one.

**Comment by alexisph** [comment]
UBI minimal, as defined in https://github.com/ibm-messaging/mq-metric-samples/blob/master/scripts/buildBuildah.sh

/etc/localtime does not have to point to anything. It can be a "fat" timezone file, mounted from a configmap, which is what i am doing. See also the redhat article i linked above for more info.

**Comment by abudavis** [comment]
@alexisph I did read the redhat page, it says the tzdata isn't installed on the UBI 8 minimal image, did you do that? I have an /etc/localtime for CEST timezone on my RHEL VM, could you I use that for the ConfigMap on Openshift?

**Comment by abudavis** [comment]
Thanks, I only had to apply ["Workaround 3"](https://access.redhat.com/solutions/2567961) and that solved the problem, thank you!

@ibmmqmet You might want to mention this fix somewhere for those customers with MQ servers on non-UTC timezone.
