### ISSUE TITLE
Connection to Distributed MQ's

### ISSUE THREAD

**Issue by kidharb** [ibm-messaging/mq-metric-samples#32]
Hi There,

We are having an issue when connecting to a distributed MQ

> ./mq_prometheus.sh
> IBM MQ metrics exporter for Prometheus monitoring
> 
> Warning: Data from 'RESET QSTATS' has been requested.
> Ensure no other monitoring applications are also using that command.
> 
> INFO[0000] Connected to queue manager  MQMBUAT01
> FATA[0013] Error subscribing to $SYS/MQ/INFO/QMGR/MQMBUAT01/Monitor/STATQ/%s/OPENCLOSE: Error subscribing to topic '$SYS/MQ/INFO/QMGR/MQMBUAT01/Monitor/STATQ/SYSTEM.BROKER.AGGR.REQUEST/OPENCLOSE': MQSUB: MQCC = MQCC_FAILED [2] MQRC = MQRC_HANDLE_NOT_AVAILABLE [2017]
> 

There are no topics on the queue manager so I would like to know if the code supports connecting to distributed MQs?

**Comment by ibmmqmet** [comment]
A HANDLE_NOT_AVAILABLE error usually means you do not have a large enough MAXHANDS attribute on the queue manager to allow all the required objects to be opened.

**Comment by kidharb** [comment]
Thanks Mark, it was set to 256.
We set it progressively upto 8192 which worked.
