### ISSUE TITLE
MQ Go Version: states 'unknown'

### ISSUE THREAD

**Issue by Bert99Blib** [ibm-messaging/mq-metric-samples#321]
Hello dear mq-metric-samples team,

Last week, I downloaded the 5.6.0 release and built the mq_prometheus alongside our existing version 5.5.0.

The installation of mq-golang (v5.6.0) went smoothly; and building mq-metrics-samples in v5.6.0 worked without a hitch.

However, when I run mq_prometheus with `--help`, I see a different output, namely:

```shell
root@WDKAGA235B [/tmp/go/bin]# ./mq_prometheus --help
IBM MQ metrics exporter for Prometheus monitoring
MQ Go Version : Unknown
```

The line with `MQ Go Version :` wasn't there in 5.5.0.

What surprises me is the value `Unknown`.

What value should be there? Should it show the version of the mq-golang libraries or the local Go version?

I've already tried to get more verbose output during the install or build process (using -x/-v), but unfortunately, I couldn't gather any further insights.

Could you please check if the issue is on my end (a Layer-8 problem) or if something else is going wrong?

Cheers!
Charly

##### Variables
Here's how I set the environment variables.:
```shell
#!/bin/env bash

# MQ-Installation angeben
export MQ_INSTALLATION_PATH=/opt/mqm

# Variablen fuer Build und Install
export CGO_CFLAGS="-I$MQ_INSTALLATION_PATH/inc"
export CGO_LDFLAGS_ALLOW="-Wl,-rpath.*"
export CGO_LDFLAGS="-L$MQ_INSTALLATION_PATH/lib64 -Wl,-rpath,$MQ_INSTALLATION_PATH/lib64"

# Pfade für die Ausgabe
export GOPATH=/opt/go-mq-monitoring
export GOROOT=/usr/lib/golang
```

##### Install and build commands
```shell
# cd to mq-golang directory
go install ./mqmetric/
go install ./ibmmq/

# cd to mq-metric-samples directory
go build  -o /tmp/go/bin/mq_prometheus ./cmd/mq_prometheus/*.go
```

##### MQ
```shell
root@WDKAGA235B [/opt/go-mq-monitoring]# dspmqver
Name:        IBM MQ
Version:     9.2.0.26
Level:       p920-026-240612
BuildType:   IKAP - (Production)
Platform:    IBM MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 4.18.0-553.8.1.el8_10.x86_64
O/S Details: Red Hat Enterprise Linux 8.10 (Ootpa)
InstName:    Installation1
InstDesc:
Primary:     Yes
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 920
LicenseType: Production
```

##### GO version
```shell
root@WDKAGA235B [/opt/go-mq-monitoring]# go version
go version go1.21.11 (Red Hat 1.21.11-1.module+el8.10.0+21986+2112108a) linux/amd64
```

**Comment by ibmmqmet** [comment]
It should be showing `v5.6.0` - the module version for the ibmmq package. I don't know why you're not getting it - something in your environment is not embedding the build information. If I run the identical compile commands on my system, I do see it. The "unknown" means that reading the debug info has failed for some reason - the only stated reason for failure at that point is that the program has not been built using modules. 

Though normally, I use one of the provided scripts or Dockerfiles to run my builds - they use the included vendor tree so I don't need to explicitly build the ibmmq/mqmetrics packages. 

If you edit `pkg/config/version.go`, you can print the output from _ReadBuildInfo()_ to see what is actually available.

**Comment by Bert99Blib** [comment]
Hello Mark,

Thank you very much for your response.

The good news is that, despite the missing display, the metrics collection is working perfectly (I conducted comparative tests).

So, for now, it's just a minor (cosmetic) issue on my end. I'll follow up on your suggestion next week and try to track down the cause of this error.

As soon as I have any new insights, I will post them here if that's okay.

**Comment by Bert99Blib** [comment]
Hello Mark,

you're right - if I print out the BuildInfo (pls. see below) I don't get any module informations.

Obviously this is an error on my side I will have to fix.

Thank you for your quick support - the issue can be closed.

```
BuildInfo: go   go1.21.11 (Red Hat 1.21.11-1.module+el8.10.0+21986+2112108a)
path    command-line-arguments
build   -buildmode=exe
build   -compiler=gc
build   DefaultGODEBUG=panicnil=1
build   CGO_ENABLED=1
build   CGO_CFLAGS=-I/opt/mqm/inc
build   CGO_CPPFLAGS=
build   CGO_CXXFLAGS=
build   CGO_LDFLAGS="-L/opt/mqm/lib64 -Wl,-rpath,/opt/mqm/lib64"
build   GOARCH=amd64
build   GOOS=linux
build   GOAMD64=v1
```

**Comment by Bert99Blib** [comment]
Update: found the human error :-)

In my environment the variable GO111MODULE was set to 'off' - thus no modules were used.

Solution:
```
export GO111MODULE=auto
```

Build informations afterwards:

```
BuildInfo: go   go1.21.11 (Red Hat 1.21.11-1.module+el8.10.0+21986+2112108a)
path    command-line-arguments
dep     github.com/beorn7/perks v1.0.1
dep     github.com/cespare/xxhash/v2    v2.2.0
dep     github.com/ibm-messaging/mq-golang/v5   v5.6.0
dep     github.com/ibm-messaging/mq-metric-samples/v5   (devel)
dep     github.com/prometheus/client_golang     v1.19.1
dep     github.com/prometheus/client_model      v0.5.0
dep     github.com/prometheus/common    v0.48.0
dep     github.com/prometheus/procfs    v0.12.0
dep     github.com/sirupsen/logrus      v1.9.3
dep     golang.org/x/crypto     v0.23.0
dep     golang.org/x/sys        v0.20.0
dep     golang.org/x/term       v0.20.0
dep     google.golang.org/protobuf      v1.34.1
dep     gopkg.in/yaml.v2        v2.4.0
build   -buildmode=exe
build   -compiler=gc
build   CGO_ENABLED=1
build   CGO_CFLAGS=-I/opt/mqm/inc
build   CGO_CPPFLAGS=
build   CGO_CXXFLAGS=
build   CGO_LDFLAGS="-L/opt/mqm/lib64 -Wl,-rpath,/opt/mqm/lib64"
build   GOARCH=amd64
build   GOOS=linux
build   GOAMD64=v1

Module: github.com/beorn7/perks Version: v1.0.1
Module: github.com/cespare/xxhash/v2 Version: v2.2.0
Module: github.com/ibm-messaging/mq-golang/v5 Version: v5.6.0
Module: github.com/ibm-messaging/mq-metric-samples/v5 Version: (devel)
Module: github.com/prometheus/client_golang Version: v1.19.1
Module: github.com/prometheus/client_model Version: v0.5.0
Module: github.com/prometheus/common Version: v0.48.0
Module: github.com/prometheus/procfs Version: v0.12.0
Module: github.com/sirupsen/logrus Version: v1.9.3
Module: golang.org/x/crypto Version: v0.23.0
Module: golang.org/x/sys Version: v0.20.0
Module: golang.org/x/term Version: v0.20.0
Module: google.golang.org/protobuf Version: v1.34.1
Module: gopkg.in/yaml.v2 Version: v2.4.0
MQ Go Version : v5.6.0
```
