### ISSUE TITLE
Requirement of gcc not mentioned

### ISSUE THREAD

**Issue by vgavinash** [ibm-messaging/mq-metric-samples#322]
In the latest steps provided, under https://github.com/ibm-messaging/mq-metric-samples?tab=readme-ov-file#building-a-component-on-your-system-directly, the `go build` will not compile unless the `gcc` is installed in Linux. I suppose this needs a mention in that particular section.

**Comment by ibmmqmet** [comment]
The README already says that a C compiler is needed in the Requirements section. It need not be gcc, although that is the default called by cgo, and the default installed alongside the Go compiler. If you want to use a different compiler (eg clang) then the Go documentation will say to set the CC environment variable first.
