### ISSUE TITLE
Unknown Filer Type Error while building

### ISSUE THREAD

**Issue by shrashar** [ibm-messaging/mq-metric-samples#324]
![17249523849615195175092611690457](https://github.com/user-attachments/assets/e3b3d90c-f850-4bb2-94bb-ca79747ad206)
Hi,

I have attached the screenshot with the details.

IBM MQ client runing on Mac Linux - 9.3.0.11
GCC complier is also installed.
 

Thank and Regards,
Shray Sharma

**Comment by ibmmqmet** [comment]
I don't know what you mean by "Mac Linux". Do you really mean MacOS? Or a Linux container?

In any case, it looks like you've mixed MacOS and Linux components, or are trying to do some kind of cross-compile. You need to use the right MQ client libraries for the OS for which you are build.

**Comment by shrashar** [comment]
Please close it as I am trying to build on my windows desktop now.
