### ISSUE TITLE
Limiting emitted metrics to a few queries

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-metric-samples#332]
We have been using the mq metrics sample for sometime now and find it very useful.
We push the MQ metrics via Prometheus to Grafana Cloud which has a monthly series limit of 15K metrics. 
Given the large number of metrics/queries emitted, for our 20+ QMGR instances that equates to 80K metrics per day of which 15K are allowed into Grafana Cloud Dashboards.

We use very few metrics such as "ibmmq_qmgr_uptime", "ibmmq_queue_depth", "ibmmq_queue_time_since_get", "ibmmq_queue_time_since_put", "ibmmq_queue_mqput_persistent_message_count" & "ibmmq_queue_attribute_max_depth". Is there someway to limit the rest of the metrics being emitted to Grafana from our prometheus instance?

**Comment by ibmmqmet** [comment]
The [TUNING](https://github.com/ibm-messaging/mq-metric-samples/blob/master/TUNING.md) document describes some ways to reduce the metric collection.

If that is not sufficient, then you'd have to apply something at the Prometheus end. [This page](https://grafana.com/docs/grafana-cloud/cost-management-and-billing/reduce-costs/metrics-costs/client-side-filtering/) seems to have some [approaches](https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus/) based around the `metric_relabel_configs` section.

**Comment by abudavis** [comment]
@ibmmqmet  Thank you! Since the change to qm.ini requires a QMGR restart to take effect, is there an alternative way of setting this? TuningParameters.MonitorPublishHeartBeat

**Comment by ibmmqmet** [comment]
No - a restart is required.

**Comment by abudavis** [comment]
@ibmmqmet Ok. I read through the Tuning doc which says:

1. _"You can disable all use of published resource metrics, and rely on the DISPLAY xxSTATUS responses. This clearly reduces the data, but you lose out on many useful metrics"_ >> what are the many useful metrics you refer to here?

2. _The filters.queueSubscriptionSelector list defines the sets of topics that you might be interested in. The complete set - for now - is [OPENCLOSE, INQSET, PUT, GET, GENERAL]_ >> If I stick to just PUT, GET, GENERAL will I miss out on metrics such as "ibmmq_queue_time_since_get", "ibmmq_queue_time_since_put", ipprocs and opprocs?

Also here, for deploying on the Kubernetes would this be correct?
`oc create configmap metrics-configuration-xxx --from-literal=IBMMQ_FILTERS_QUEUESUBSCRIPTIONSELECTOR='[PUT, GET, GENERAL]'`

For example, this is what I plan to set for the first point above:
`oc create configmap metrics-configuration-xxx --from-literal=IBMMQ_GLOBAL_USEPUBLICATIONS='false'`

**Comment by ibmmqmet** [comment]
If you want to see exactly what metrics come from which command, then you can run the MQSC command `DISPLAY QSTATUS` (and similar for the other object types), and the sample program `amqsrua`. But in particular, disabling all use of publications will remove almost all of the qmgr-level metrics

**Comment by abudavis** [comment]
@ibmmqmet I see. We only need the qmgr level metric "ibmmq_qmgr_uptime", would that be available if "global.usePublications=false"?
Also what's the default value of "global.pollInterval"? Is this the same as the MQ tuning param MonitorPublishHeartBeat?

**Comment by abudavis** [comment]
@ibmmqmet I could see that the default value of "global.pollInterval" from the code is "0s". What is the implication of setting this to match the qm.ini MonitorPublishHeartBeat (60 seconds)?
https://github.com/ibm-messaging/mq-metric-samples/blob/master/pkg/config/config.go
