### ISSUE TITLE
MQ Prometheus Exporter - MQRC_UNEXPECTED_ERROR [2195]

### ISSUE THREAD

**Issue by gnaveen33** [ibm-messaging/mq-metric-samples#334]
Hi Team,

We are getting below error while trying start the Prometheus service for our queue manager. 

level=error msg="Connection to QMGR has failed. Cannot open queue SYSTEM.DEFAULT.MODEL.QUEUE : MQOPEN: MQCC = MQCC_FAILED [2] MQRC = MQRC_UNEXPECTED_ERROR [2195]"

**Comment by ibmmqmet** [comment]
2195 usually means something serious is wrong inside the qmgr or its environment. Nothing to do with this package. Look at the FDCs and error logs. And if necessary, open a support ticket
