### ISSUE TITLE
Downloading a message [RFE]

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-metric-samples#337]
We are extremely pleased with this tool, there really isn't a replacement.

I was wondering although this may have been created purely for monitoring, have you ever considered on extended functionality in terms of the ability to download (MQGET/MQBROWSE) a message from queues?

Our setup:
```
mq-metric-prometheus v5.6.0
MQ Servers on RHEL: v9.3.0.15
MQ metric pods on Openshift pull metrics from MQ servers deployed in sites which are 50ms away.
```

**Comment by ibmmqmet** [comment]
No. Not something that I think is appropriate for a monitoring project.

There are already plenty of tools available to work with messages, including `dmpmqmsg`, and the samples like `amqsbcg` shipped in the MQ product itself.
