### ISSUE TITLE
Need to monitor all the queues and channels

### ISSUE THREAD

**Issue by rputtur** [ibm-messaging/mq-metric-samples#338]
Hi Team,

Kindly let us know how to monitor all the queues and channels using this. Can we pass * in the below variables to monitor all the queues and channels?
ibmmq.monitoredQueues
ibmmq.monitoredChannels

Also kindly let us know, the best way to push queue manager error logs through otel. 

Thanks in advance

**Comment by ibmmqmet** [comment]
You CAN use "*" to monitor all queues and channels but that might give more objects than you care about. It's the kind of thing you could easily have tried of course.

For OTel logging, see [here](https://marketaylor.synology.me/?p=1542)
