### ISSUE TITLE
Metrics listing all the applications connected to read and write to the queue

### ISSUE THREAD

**Issue by rputtur** [ibm-messaging/mq-metric-samples#355]
Hi team,

We see that there are metrics to show the count of open handles on a MQ Queue. Kindly let us know if there is any metrics listing all the applications connected to read and write to the queue. 

Thank you for all the support!

thanks
Ravi

**Comment by ibmmqmet** [comment]
No. Application Names are strings, not metrics and do not fit well into metrics databases. They also do not belong well as tags on object names, as they tend to vary too rapidly.

You can get the information with MQSC commands like `DISPLAY QSTATUS(*) TYPE(HANDLE)` and `DISPLAY CONN(*) TYPE(HANDLE)` but the responses really don't fit the metrics patterns.

The metrics-based approach is to have a threshold or expected number of open handles against an object, and then only take some action if the actual value is outside the normal range.

**Comment by rputtur** [comment]
Hi Mark,

Thanks a lot for your inputs.

Thanks
Ravi Puttur
