### ISSUE TITLE
mq_aws not gathering statistics due to missing config "usePublications"

### ISSUE THREAD

**Issue by davidcallen** [ibm-messaging/mq-metric-samples#36]
Using Master with Latest commit of 042f1ef on 2 Apr.

I found that using mq_aws to export from IBM MQ v9.1 to CloudWatch that it was not gathering any statistics. This was due to a missing config "usePublications". 

In mq-golang/mqmetric/discover.go it was exiting the function discoverStats() early at the test 'if metaPrefix == "" && !usePublications {'

In mq-metric-samples/cmd/mq_aws/config.go I needed to add this code change to set that config parameter : 

```
diff --git a/cmd/mq_aws/config.go b/cmd/mq_aws/config.go
index dfe2e86..7892788 100644
--- a/cmd/mq_aws/config.go
+++ b/cmd/mq_aws/config.go
@@ -62,6 +62,7 @@ func initConfig() {
        flag.StringVar(&config.namespace, "ibmmq.namespace", "IBM/MQ", "Namespace for metrics")
 
        flag.BoolVar(&config.cc.ClientMode, "ibmmq.client", false, "Connect as MQ client")
+       flag.BoolVar(&config.cc.UsePublications, "ibmmq.usePublications", true, "Use resource publications. Set to false to monitor older Distributed platforms")
 
        flag.StringVar(&config.interval, "ibmmq.interval", "60", "How many seconds between each collection")
        flag.IntVar(&config.maxErrors, "ibmmq.maxErrors", 10000, "Maximum number of errors communicating with server before considered fatal")
```

After this fix it would gather statistics for QueueManager and Queues and export them into CloudWatch.

**Comment by ibmmqmet** [comment]
Thanks for pointing that out. I'm trying to go through all the exporters right now to bring them all up to a common feature set so I'll make sure this gets fixed in that work.

**Comment by davidcallen** [comment]
Thanks, that would be great.

**Comment by ibmmqmet** [comment]
v5.0.0 should have resolved this - all the exporters now have common config options and the addition of a YAML file which should be simpler than command-line flags.

**Comment by davidcallen** [comment]
Sounds great. Thanks very much
