### ISSUE TITLE
Error while building main.go

### ISSUE THREAD

**Issue by AbinayaSundarrajan** [ibm-messaging/mq-metric-samples#37]
Tried to build the main.go file using gitbash on a windows go environment. 
Facing the below error:
$ go build -o main.go
# vendor/github.com/ibm-messaging/mq-golang/mqmetric
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\channel.go:274:44: undefined: ibmmq.MQCFH
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\channel.go:513:32: undefined: ibmmq.MQCFH
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\discover.go:65:26: undefined: ibmmq.MQObject
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\discover.go:1060:39: undefined: ibmmq.PCFParameter
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\mqif.go:264:41: undefined: ibmmq.MQObject
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\mqif.go:292:39: undefined: ibmmq.MQObject
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\mqif.go:300:46: undefined: ibmmq.MQObject
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\mqif.go:304:50: undefined: ibmmq.MQObject
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\qmgr.go:175:45: undefined: ibmmq.MQCFH
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\queue.go:333:42: undefined: ibmmq.MQCFH
..\..\..\vendor\github.com\ibm-messaging\mq-golang\mqmetric\queue.go:333:42: too many errors

**Comment by ibmmqmet** [comment]
The command you have shown `go build -o main.go` cannot be correct as it's trying to create output over a source file. Please use the commands shown in the README or in the `buildMonitors.sh` script

**Comment by alxzndr** [comment]
The above build command is indeed incorrect and will overwrite the source files.

I do get the same undefined object errors when trying to build windows executables with the buildMonitors.sh script. To do this I have added `export GOOS="windows"` to the buildInDocker.sh script.

`Building mq_aws
# github.com/ibm-messaging/mq-golang/v5/mqmetric
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:274:44: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:513:32: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/discover.go:65:26: undefined: ibmmq.MQObject
Building mq_coll
# github.com/ibm-messaging/mq-golang/v5/mqmetric
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:274:44: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:513:32: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/discover.go:65:26: undefined: ibmmq.MQObject
Building mq_influx
# github.com/ibm-messaging/mq-golang/v5/mqmetric
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:274:44: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:513:32: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/discover.go:65:26: undefined: ibmmq.MQObject
Building mq_json
# github.com/ibm-messaging/mq-golang/v5/mqmetric
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:274:44: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:513:32: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/discover.go:65:26: undefined: ibmmq.MQObject
Building mq_opentsdb
# github.com/ibm-messaging/mq-golang/v5/mqmetric
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:274:44: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:513:32: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/discover.go:65:26: undefined: ibmmq.MQObject
Building mq_prometheus
# github.com/ibm-messaging/mq-golang/v5/mqmetric
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:274:44: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:513:32: undefined: ibmmq.MQCFH
vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/discover.go:65:26: undefined: ibmmq.MQObject
Compiled programs should now be in /home/alexander/tmp/mq-metric-samples/bin
`
No .exe files are found in the output folder. 
When building for linux all is working fine and the bin files are available in the output folder.

**Comment by paologallinaharbur** [comment]
I believe I hit the same issue.
Since it is using some platform dependent C headers that are installed with the product itself you cannot simply "cross-compile". 
You should compile it from windows.
