### ISSUE TITLE
Channel metrics not collected if not in running status

### ISSUE THREAD

**Issue by davidcallen** [ibm-messaging/mq-metric-samples#38]
Thanks for mq-metrics!   I think I have found this following issue.
I am using the mq-metrics-samples/mq_influx and importing into an InfluxDB. 
I am collecting metrics on a pattern list of Queues and for all Channels ("-ibmmq.monitoredChannels=*")
I have an Alert in Grafana and Kapacitor to detect when any of the Channels have Status that is not Running (value=3).

Observed Behaviour
---------------------------
I do not receive any metrics on Channels that have Status != Running (value of 3).
Note: This may be limited to just Channels of Type (Requestor and Receiver).

Expected Behaviour
--------------------------
I would expect to receive metrics on all the Channels on my list of Queues regardless of their Status (Running, Inactive, ...)

I can somewhat workaround this issue in Grafana and Kapacitor Alerts by having a Query for each Channel and detecting Missing data and alerting on that but it is a very awkward solution.
Note: This solution doesnt help for some Channels that I do not want to alert on if in Inactive Status (my Receiver Channels).

I have looked through the source code and cannot see any obvious code that would do a "do not discover or export channels if Status != Running"

**Comment by davidcallen** [comment]
Fair warning : I am only vaguely familiar with IBM MQ so have significant ignorance in this area.

I notice that if I use runmqsc commands to get my Receiver channel status I have no info with either  CURRENT or SAVED data : 

`DISPLAY CHSTATUS(LNTPSL_P0385200.C1) CURRENT
     7 : DISPLAY CHSTATUS(LNTPSL_P0385200.C1) CURRENT
AMQ8420I: Channel Status not found.`

`DISPLAY CHSTATUS(LNTPSL_P0385200.C1) SAVED
     8 : DISPLAY CHSTATUS(LNTPSL_P0385200.C1) SAVED
AMQ8420I: Channel Status not found.`

I suspect this code is related to my issue [channel.go : fn collectChannelStatus()]
It gets channels by call to MQCMD_INQUIRE_CHANNEL_STATUS
See https://www.ibm.com/support/knowledgecenter/SSFKSJ_7.5.0/com.ibm.mq.ref.adm.doc/q087540_.htm
The below code in fn CollectChannelStatus() looks suspicious - like someone has had an attempt to solve issue same or similar to mine : 

// This would allow us to extract SAVED information too
errCurrent := collectChannelStatus(pattern, ibmmq.MQOT_CURRENT_CHANNEL)
err = errCurrent
//errSaved := collectChannelStatus(pattern, ibmmq.MQOT_SAVED_CHANNEL)
//if errCurrent != nil {
//	err = errCurrent
//} else {
//	err = errSaved
//}

**Comment by ibmmqmet** [comment]
Inactive channels will never show up in CURRENT status and will not always be seen in SAVED status either. While I had played with reporting on SAVED status, it did not seem particularly useful so I never enabled that block of code. Channels which are explicitly STOPPED are different, and do show up in the status.

Being able to see the status of all channels including the INACTIVE ones might be useful but could overwhelm tables. I'll think about adding it as a configurable option in the future.

**Comment by ibmmqmet** [comment]
showInactiveChannels is a new config option with v5.1.0 released last week

**Comment by davidcallen** [comment]
Thanks for the fix.  I'll take a look asap

**Comment by ibmmqmet** [comment]
closing as delivered
