### ISSUE TITLE
Compile issue: github.com/aws/aws-sdk-go@v1.30.18: connection refused

### ISSUE THREAD

**Issue by fnuzzi** [ibm-messaging/mq-metric-samples#39]
Hi Mark.
I am trying to compile your latest mq_metrics v 5.0.0 package which uses go modules to make use of the new -ibmmq.QueueSubscriptionFilter option (BTW, thanks for adding it).
But I am getting the following error:
go build -o $GOPATH/bin/mq_prometheus ./cmd/mq_prometheus/*.go
go: github.com/aws/aws-sdk-go@v1.30.18: Get "https://proxy.golang.org/github.com/aws/aws-sdk-go/@v/v1.30.18.mod": dial tcp 172.217.16.177:443: connect: connection refused

I am compiling on a Linux machine that has no external access. Is there any workaround?

**Comment by ibmmqmet** [comment]
Add `-mod=vendor` as in the buildInDocker.sh script

**Comment by fnuzzi** [comment]
Thanks, it did work
