### ISSUE TITLE
Client connections in YAML config

### ISSUE THREAD

**Issue by njchaltry** [ibm-messaging/mq-metric-samples#40]
Hi Mark,

Is it possible to add the host, port and channel information for client connections to the exporter's YAML config? 

All of the queue managers that I'd like to connect to are remote on z/OS and reside on multiple hosts. I'm assuming that I will need to run a program for each queue manager that I want to connect to but I don't know how to specify unique MQSERVER environment variables for each connection.

Thanks!

**Comment by ibmmqmet** [comment]
This is in v5.1.0 released last week

**Comment by ritessh** [comment]
Hello, How do I pass User SSL cert and TrustStore for TLS authentication? I don't see parameter there.

**Comment by ibmmqmet** [comment]
The explicit config parameters for client channels are deliberately kept minimal. More complex requirements such as TLS ciphers are set instead through a CCDT entry. And then the keystore is set in the usual external way for C-based clients - the MQSSLKEYR environment variable. See https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.sec.doc/q012740_.htm

**Comment by ritessh** [comment]
> The explicit config parameters for client channels are deliberately kept minimal. More complex requirements such as TLS ciphers are set instead through a CCDT entry. And then the keystore is set in the usual external way for C-based clients - the MQSSLKEYR environment variable. See https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.sec.doc/q012740_.htm

Hello, Thanks for providing solution!
I tried above solution and I'm getting "MQRC_SSL_INITIALIZATION_ERROR [2393]" error. Any idea about it?
I suspect i'm getting this error because we are running client program in docker container and  MQ service side it is not able resolve correct hostname causing this issue.

Is there anyway I setup this exporter on VM where I don't have internet connectivity and I cannot perform GO build?

**Comment by ibmmqmet** [comment]
There are a lot of reasons for that error code. There's often something in the error logs (AMQERR*.LOG) on either the client or qmgr side that can give more information. Most common reasons include

* local keystore not accessible
* certificate (or signing cert from CA) not in partner's keystore
* invalid/non-matching cipherspec between partners

**Comment by ritessh** [comment]
Appreciate prompt response!
Is there anyway I setup this exporter on VM where I don't have internet connectivity and I cannot perform GO build?

**Comment by ibmmqmet** [comment]
The code is only available as source. You have to find a way to build it yourself.

**Comment by ibmmqmet** [comment]
closing as answered

**Comment by sumitbsn** [comment]
Hi @ibmmqmet!! I want to connect to a queue manager remotely and ssl is configured for that queue manager. As you mentioned in the above comment "More complex requirements such as TLS ciphers are set instead through a CCDT entry. And then the keystore is set in the usual external way for C-based clients - the MQSSLKEYR environment variable.".

Could you please explain more, how i can use CCDT with the below command? Also, MQSSLKEYR  has to be used with the below command or we can set it as env variable in Linux?

`./mq_prometheus -ibmmq.client=true -ibmmq.connName="192.168.56.104(1414)" -ibmmq.channel=SYSTEM.ADMIN.SVRCONN -ibmmq.userid='mqtes' -ibmmq.password='mqtes' -ibmmq.queueManager=QM1 -ibmmq.monitoredQueues=q*,test* -ibmmq.monitoredChannels=* -ibmmq.useStatus -ibmmq.httpListenPort=9157 -log.level=info`

**Comment by amiga23** [comment]
@ibmmqmet did you solve your issue? It seems the IBM guys do not really want that someone uses their software ;-)
