### ISSUE TITLE
MQ Monitoring - Docker image

### ISSUE THREAD

**Issue by ssnmworld** [ibm-messaging/mq-metric-samples#41]
Hi - I have couple of questions regarding this monitoring. 

1. There is not enough information regarding the docker implementation. I have successfully built the docker image, but not sure how to run and what kind of parameter it takes. I am basically running the monitor in the client mode.

2. I have multiple queue managers in an environment. Does this suite support multiple queue managers? 

3. What is the preferred IDE for viewing this monitoring code ? 

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.

**Comment by ibmmqmet** [comment]
The Dockerfile in this repo is there to assist with compiling the programs, not for running them. Once you've got the binaries built, then you can build your own container to hold the particular collector you want, along with any startup script and a suitable configuration file (copied into the container or mounted from the host). Any runtime container must also include the MQ client libraries - the Dockerfile here can be used as an example of how to obtain that if you don't already have a copy. Each of the collectors has an example startup script to give an idea of the parameters you may need to set, or look at the corresponding yaml files.

Each collector connects to only a single queue manager. 

I don't use any IDE for Go code. I just use a regular editor (usually Atom, but sometimes vi or VSCode) , Makefiles, scripts etc.

**Comment by ssnmworld** [comment]
Can you provide examples for building a docker image for using the exporter with prometheus backend? I can successfully build the image, but not quite sure how about configuring and running the container so I can collect metrics.

I am using the client version of the exporter.

Thanks

**Comment by ibmmqmet** [comment]
Added some examples in the `scripts` subdirectory.

**Comment by ibmmqmet** [comment]
#42 is essentially a duplicate, with a bit more info in it. So closing this one.
