### ISSUE TITLE
Integrate Prometehus with MQ from a Client computer

### ISSUE THREAD

**Issue by ConsultandJr** [ibm-messaging/mq-metric-samples#43]
Hi all,

We are just trying to do the integration for monitoring, but we have a question, if it is possible to run the scripts that collect the metrics on a client computer.
Pointing

-IP-HOST MQ
-QueueManageme
-Port
-Channel

We don't want to install or run anything on the QManager server.
It is possible to carry out this configuration and which file should we install on the client that would serve as a pivot

Please your help to make this implementation.

Thank you very much

Please include the following information in your ticket.

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.

**Comment by ibmmqmet** [comment]
Look at the yaml configuration files, and specific READMEs such as https://github.com/ibm-messaging/mq-metric-samples/blob/master/cmd/mq_prometheus/README.md 

Also look at the build and run scripts in the `scripts` subdirectory of the repo.

**Comment by mariofuentesgon** [comment]
Hello, thank you very much for answering.

But I'm a bit confused, I don't know what scripts I should run as a client in a pivot, and put these parameters:

ibmmq.client:true

-IP MQ
-QueueManagerName
-Port
-Channel

Please give me a hand.

Thank you.

**Comment by ConsultandJr** [comment]
For the moment we have solved with:
https://github.com/Cinimex-Informatica/mq-java-exporter#mq-constants-mapping

Thank you
