### ISSUE TITLE
time="2020-08-27T15:21:38-03:00" level=error msg="Must provide a queue manager name to connect to."

### ISSUE THREAD

**Issue by AlexAlvesJr** [ibm-messaging/mq-metric-samples#45]
Please include the following information in your ticket.

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.

Hello, Mark!

First of all, thanks for making this programs available for us. They are really helpful!

We are trying to build the monitor here in a Windows machine and finally we could build the mq_prometheus.exe and the yaml file, but when we try to start it we receive the following error in the sysout:
"time="2020-08-27T15:21:38-03:00" level=error msg="Must provide a queue manager name to connect to.""

It's weird, because we are passing the name of the qmgr in the MQ service and in the yaml file either. like this:
"global:
  useObjectStatus: true
  useResetQStats: false
  logLevel: INFO 
  metaprefix: ""
  pollInterval: 30s
  rediscoverInterval: 1h
  tzOffset: 0h

connection:
    queueManager: Alex"

The client connection isn't being used:
clientConnection: false

Could you give us a hand, please?

Best Regards,
Alex

**Comment by ibmmqmet** [comment]
First thing I'd do is set logLevel to DEBUG to see if the YAML is loaded at all (perhaps set it on the command line rather than in the YAML just to make sure). I've also seen that the Go YAML parser sometimes fails silently when there's any syntax errors in the file. For example, not having a space after the colons,

**Comment by AlexAlvesJr** [comment]
Thanks, Mark! :)

**Comment by ibmmqmet** [comment]
closing as no further activity
