### ISSUE TITLE
Channel stat: totalbytes

### ISSUE THREAD

**Issue by a359089** [ibm-messaging/mq-metric-samples#46]
I do not see there is a metric for channel totalbytes, or I missed it somehow? Thx,

**Comment by ibmmqmet** [comment]
The current version doesn't capture the bytessent/rcvd from channel status (though it does have number of messages transferred). The bytes and buffer values are in my devt stream, so those attributes will appear on the next update.

**Comment by a359089** [comment]
Thanks for the confirmation. What's the estimated time for next update?

**Comment by ibmmqmet** [comment]
I don't have a schedule. Depends on when there's time to work on various things. Probably during this month but that's all I can say.

**Comment by ibmmqmet** [comment]
v5.1.2 released today

**Comment by a359089** [comment]
Do that include totalbytes? i do not see it.

**Comment by ibmmqmet** [comment]
There are now per-channel byte counts which are the metrics available from MQ. `ibmmq_channel_bytes_sent` and `ibmmq_channel_bytes_rcvd`. Creating totals can then be done using aggregation functions in Prometheus.

**Comment by a359089** [comment]
Got it. I was looking for the word 'total'. 

An unrelated quick question,  should I only use mq_prometheus binary with the same version of MQ against which it was compiled?

**Comment by ibmmqmet** [comment]
That's not necessary. MQ connections are forwards and backwards compatible. A V9.2 client program can connect to a V9.1 qmgr.

The only caveat is that the usual rule about shared libraries applies - don't compile against version X+1 and try to run the binary on a system which only has version X of a product's shared libs  (like the MQ runtime libraries) installed.

**Comment by a359089** [comment]
Thx Mark. I am closing this issue.
