### ISSUE TITLE
When I try to build the pkg getting below error.

### ISSUE THREAD

**Issue by karthickraj19** [ibm-messaging/mq-metric-samples#47]
When I try to build the pkg getting below error.
Followed all the steps specified in the Readme but still getting this error.

export GOPATH=/tmp/MQ_Monitor/go
export GOROOT=/XXX/XXX/XXX/XXX/XXX/go/go1.14.7.linux_amd64-1.14.7/go1.14.7.linux_amd64/go
export GOPROXY=http://goproxyXXX.XXXX.XXX.XXX.com
export CGO_ENABLED=0

bash-4.2$ go build -o $GOPATH/bin/mq_prometheus ./cmd/mq_prometheus/*.go
go: downloading github.com/prometheus/client_golang v1.6.0
go: downloading github.com/ibm-messaging/mq-golang/v5 v5.1.1
go: downloading github.com/sirupsen/logrus v1.5.0
go: downloading gopkg.in/yaml.v2 v2.2.5
go: downloading golang.org/x/sys v0.0.0-20200420163511-1957bb5e6d1f
go: downloading golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/common v0.9.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/prometheus/procfs v0.0.11
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/golang/protobuf v1.4.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading google.golang.org/protobuf v1.21.0
# github.com/ibm-messaging/mq-golang/v5/mqmetric
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/channel.go:305:44: undefined: ibmmq.MQCFH
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/channel.go:544:32: undefined: ibmmq.MQCFH
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/discover.go:65:26: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/discover.go:1079:39: undefined: ibmmq.PCFParameter
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/mqif.go:93:12: undefined: ibmmq.MQReturn
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/mqif.go:325:41: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/mqif.go:353:39: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/mqif.go:361:46: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/mqif.go:365:50: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/qmgr.go:175:45: undefined: ibmmq.MQCFH
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.1/mqmetric/qmgr.go:175:45: too many errors

**Comment by ibmmqmet** [comment]
Why have you set CGO_ENABLED=0? That will disable the C compiler.

**Comment by karthickraj19** [comment]
Ok, Is C compiler mandate for Linux? If yes, I will add the executable and set the path and will try again.
I was get the below error so disabled it.

 ERROR : exec: "gcc": executable file not found in $PATH in Linux 

So,if I add the c compiler both the error will be fixed?

**Comment by ibmmqmet** [comment]
Since it's using cgo, then yes you need a C compiler installed.

**Comment by karthickraj19** [comment]
This worked and thank for the quick turnaround.
I have one more common questions, I see there are many metrics this exporter generates.

Can we specifically limit the number of metrics by selecting only the metrics which i want. 

And for example if I say I need only the below mentioned metrics type,can we filter that on an exporter level?

# TYPE ibmmq_qmgr_channel_initiator_status gauge
# TYPE ibmmq_qmgr_command_server_status gauge
# TYPE ibmmq_qmgr_connection_count gauge
# TYPE ibmmq_qmgr_exporter_publications gauge
# TYPE ibmmq_qmgr_uptime gauge
# TYPE ibmmq_queue_attribute_max_depth gauge
# TYPE ibmmq_queue_attribute_usage gauge
# TYPE ibmmq_queue_input_handles gauge
# TYPE ibmmq_queue_oldest_message_age gauge
# TYPE ibmmq_queue_output_handles gauge
# TYPE ibmmq_queue_qtime_long gauge
# TYPE ibmmq_queue_qtime_short gauge
# TYPE ibmmq_queue_time_since_get gauge
# TYPE ibmmq_queue_time_since_put gauge

**Comment by ibmmqmet** [comment]
There is a limited ability to filter some of the queue-based metrics (see the `queueSubscriptionSelector` configuration flag) but that filter will not influence any of the items you have listed. Everything gets collected and then you filter in your dashboards and queries as to which items are of interest to you.

**Comment by vlucian** [comment]
hi. I have a similar issue. I'm able to compile it on Linux for Linux but trying to compile it on Linux for Windows doesn't work and produces the same errors as the ones above. For Linux compilation I'm using the Linux redistributable while for Windows I'm using the Windows redistributable with options GOOS=windows  GOARCH=amd64. I also played with CGO_CFLAGS and CGO_LDFLAGS and in the end, I tried with a dirty trick: I copied the content of bin64 into lib64 and also from tools/c/include directly into inc. I'm using /opt/mqm as MQ_INSTALLATION_PATH (as my understanding is /opt/mqm/lib64 and /opt/mqm/inc are the default locations for libs and include files). However no matter what I tried I got the same error...I feel I'm missing something.

**Comment by ibmmqmet** [comment]
One way of trying to cross-compile Go code, especially for such different platforms as Linux->Windows, is explained [here](https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/) I've no idea whether that would work for the MQ packages, but it will give an idea of the complexity in trying to do it. It's not something I'd want to spend time on...I'd rather spin up virtual machines or containers (depending on my preferred "host" OS) and build in those as if it's native.

**Comment by vlucian** [comment]
I did it for windows exporter: I compiled it on Linux. For MQ I feel it's a bit more complex because of the prerequisites and I was thinking someone might have "the recipe". Anyway, I'm in Azure devops and I'm not sure how is easy is to get a gcc compiler into a windows image (by default I think there's MS visual C++)

**Comment by ibmmqmet** [comment]
The post I linked to shows how you can get containers that have all the pieces needed to run a windows-compatible compiler. And shows building against native code. It looks plausible as a solution, even if you'd have to adapt it a bit for the MQ dependencies instead of the remoteAudio that they show.

**Comment by vlucian** [comment]
In the end it worked by using gcc-mingw-w64.
so:
      curl https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/9.2.0.1-IBM-MQC-Redist-Win64.zip -o /tmp/9.2.0.1-IBM-MQC-Redist-Win64.zip
      unzip /tmp/9.2.0.1-IBM-MQC-Redist-Win64.zip -d /opt/mqm
      sudo apt-get install gcc-multilib
      sudo apt-get install gcc-mingw-w64
and then:
      CGO_LDFLAGS: -L/opt/mqm/bin64 -lmqm 
      CGO_CFLAGS: -I/opt/mqm/tools/c/include/ -D_WIN64
      CXX_FOR_TARGET: x86_64-w64-mingw32-g++ 
      CXX: x86_64-w64-mingw32-g++ 
      CC_FOR_TARGET: x86_64-w64-mingw32-gcc
      CC: x86_64-w64-mingw32-gcc

I hope this will help others.
