### ISSUE TITLE
Can this be used to monitor MQ in Containers?

### ISSUE THREAD

**Issue by lsabados** [ibm-messaging/mq-metric-samples#48]
Please include the following information in your ticket.

- mq-metrics-samples version(s) that are affected by this issue.
- A small code sample or description that demonstrates the issue.

**Comment by lsabados** [comment]
Has anyone used this to monitor MQ in containers?

**Comment by ibmmqmet** [comment]
Closing as noone has responded (though there certainly are people using this to monitor MQ in containers)
