### ISSUE TITLE
Problem with yaml config file

### ISSUE THREAD

**Issue by piotrekbed** [ibm-messaging/mq-metric-samples#50]
I can't use configuration yaml file. 

mq-metric-samples in the newest version. 
go version go1.15.2 linux/amd64

`IBM MQ metrics exporter for Prometheus monitoring

INFO[0000] Connected to queue manager  ORANGE           
INFO[0000] IBMMQ Describe started                       
INFO[0000] Platform is UNIX                             
panic: http: invalid pattern

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0xd387e0, 0x0, 0x0, 0xa20a40, 0xc00027c5a0)
	/opt/go/src/net/http/server.go:2427 +0x305
net/http.Handle(...)
	/opt/go/src/net/http/server.go:2476
main.main()
	/root/go/src/src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/main.go:112 +0x3b1
`

Default yaml file from repo (github.com/ibm-messaging/mq-metric-samples/config.common.yaml)

**Comment by ibmmqmet** [comment]
That yaml file is the common set of configuration for all the collectors. The build scripts create an mq_prometheus.yaml by adding the prometheus-specific attributes that are in its subdirectory. Or you can do that by hand with however you are building it. I might add some additional default assumptions for the yaml config in future, but the combined file would have those defaults in it

**Comment by piotrekbed** [comment]
Thx. It works.
