### ISSUE TITLE
IP binding address

### ISSUE THREAD

**Issue by asunix** [ibm-messaging/mq-metric-samples#51]
Hi thanks for the amazing work.

This is not an issue.
I'am using mq export for prometheus on a multi homed host, is possibile to bind the exporter on a specific ip address ?

Thank you.

**Comment by ibmmqmet** [comment]
That's not possible in the current code, but it could probably be added as a new config option. To modify the call to `http.ListenAndServe` that's made. Today it will always bind to all addresses. I might consider it for a future update, or someone could submit a PR if it's important.

**Comment by asunix** [comment]
Thank you Mark.
