### ISSUE TITLE
Error running monitor in container with non-root user (OpenShift)

### ISSUE THREAD

**Issue by fglaeser** [ibm-messaging/mq-metric-samples#52]
Please include the following information in your ticket.

- mq-metrics-samples version(s) that are affected by this issue.

v5.1.2

- A small code sample or description that demonstrates the issue.

```
AMQ6300E: Directory '/usr/games/IBM' could not be created: '☺'.

```

I've this problem running in Openshift, for that reason I ran the container with docker with a different user (games) with the same result as I got in openshift. ( Same message )

Extra Information: The running container was created with the  Dockerfile.run.

Is there a way to run the container with a non-root user?

BR
Facundo

**Comment by ibmmqmet** [comment]
The MQ client code needs to have access to a directory for recording things like error logs. Usually this
will be under $HOME/IBM. But that can be controlled by the MQ_OVERRIDE_DATA_PATH environment variable. Set that to a path that a) exists and b) which the user running has access to. 

See https://www.ibm.com/support/knowledgecenter/SSFKSJ_latest/com.ibm.mq.ins.doc/q122885_.htm

Under OpenShift there may be additional considerations about which userids can actually be used, and that might affect whether someone has access to the default directory (the id might not even have a $HOME) but you don't need to run as root.

**Comment by fglaeser** [comment]
Thanks, I've used the MQ_OVERRIDE_DATA_PATH and it works.
BR
Facundo
