### ISSUE TITLE
Can't connect to Queue Manager

### ISSUE THREAD

**Issue by HamHamTime** [ibm-messaging/mq-metric-samples#53]
I can't seem to connect to our Queue Manager.  I am using a passwordless user account but it keeps returning the message " MQCC = " MQCC_Failed [2] MQRC_HOST_NOT_AVAILABLE [2538]. Is there a way to specify the Queue manager port you are connecting to? I'm able to connect to the queue using a different application. Any ideas would help.

**Comment by ibmmqmet** [comment]
You don't say how you are configuring the connection. There are lots of ways of doing it. But whichever mechanism is used, the hostname and port are combined. For example, "connName: localhost(1415)"

**Comment by HamHamTime** [comment]
Thanks for the quick reply. After I build the application using the command below: 
#go build -o $GOPATH/bin/mq_prometheus ./cmd/mq_prometheus/*.go
 
I will then execute the program on the same server as the Queue manager:
$GOPATH/bin]# ./mq_prometheus -ibmmq.queueManager="QM Name here" -ibmmq.channel="channel name here" -ibmmq.userid="username here"

Enter password for MQ: 
<username password is passwordless>

Output result:
FATA[0002] Cannot connect to queue manager XXXXX : MQCONNX: MQCC = " MQCC_Failed [2] MQRC_HOST_NOT_AVAILABLE [2538].

> You don't say how you are configuring the connection. There are lots of ways of doing it. But whichever mechanism is used, the hostname and port are combined. For example, "connName: localhost(1415)"

**Comment by ibmmqmet** [comment]
So you've not set the `ibmmq.connName` parameter which gives the host/port value

**Comment by HamHamTime** [comment]
Thanks that resolved that issue. I also had to create a new user with a password as I couldn't get a passwordless user to connect to our queue manager.
