### ISSUE TITLE
Label for hostname

### ISSUE THREAD

**Issue by jstelma** [ibm-messaging/mq-metric-samples#55]
Hi,

I have queue managers running on Windows Server as resources in multi-node Failover Cluster.
I'm using metrics in Prometheus and dashboards in Grafana, these are working great.
But I have one problem with Alertmanager. Alerts from Alertmanager are sent to our alerting system where we need to know the hostname on which queue manager is running at given moment.
Can you add hostname as one of labels on all metrics (like platform and qmgr)? Maybe with on/off switch in configuration for those who don't need it?

Thanks

**Comment by ibmmqmet** [comment]
There is an `instance` label already available which by default will probably have the address/name and port of the collector program. There are ways you can rewrite that too in the Prometheus configuration if it helps. See [this article](https://www.robustperception.io/controlling-the-instance-label) for example. 

But a further issue is that the collector program itself may not have any idea of which specific host on which a qmgr is running, so it's not something that could be added. For example, if connecting as a client and using a CCDT or a CONNAME with a list of addresses (typical in a multi-instance setup), there's no status information on the qmgr that says the current hostname and the MQ client does not expose which system it's actually ended up on. 

If you have a tool looking at qmgr event messages, then the QMgr Started event does have a hostname but those events are not the kind of thing you put into a prometheus metrics database - they are much more text-based.

**Comment by jstelma** [comment]
I cannot use an 'instance' label in this case because it has virtual DNS name that is a resource in Failover Cluster, not specific hostname.
I'm running Prometheus collectors as services in queue managers. I thought you could add call to os.Hostname() in the collector code but I forgot that a collector can also connect as a client.

**Comment by ibmmqmet** [comment]
This is not someething I'm going to add to the Prometheus collector, but see https://marketaylor.synology.me/?p=838 which shows how events and error logs can be ingested into Grafana's Loki (or other JSON-consuming tools). Those logs and events do have the hostname available.
