### ISSUE TITLE
Cannot  build agent to influxdb

### ISSUE THREAD

**Issue by Kohinor46** [ibm-messaging/mq-metric-samples#56]
I try to build code to win and influxdb, but got error:

> `github.com/ibm-messaging/mq-golang/v5/mqmetric
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/channel.go:338:44: undefined: ibmmq.MQCFH
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/channel.go:592:32: undefined: ibmmq.MQCFH
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/discover.go:65:26: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/discover.go:1156:39: undefined: ibmmq.PCFParameter
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/mqif.go:93:12: undefined: ibmmq.MQReturn
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/mqif.go:334:41: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/mqif.go:365:39: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/mqif.go:373:46: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/mqif.go:377:50: undefined: ibmmq.MQObject
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/qmgr.go:193:45: undefined: ibmmq.MQCFH
../../../../pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.1.3/mqmetric/qmgr.go:193:45: too many errors`

How you see errors in ibm-messaging packet, and it's too many to fix it by myself. Or i do something wrong?

**Comment by ibmmqmet** [comment]
That's the kind of error message that you might see if you haven't installed the MQ client code in advance, or have not installed it in the default location `C:\Program Files\IBM\MQ`.

And from the README: 

> There is a `buildMonitors.bat` file that may help with building on Windows. It assumes you have the [tdm-gcc-64](https://jmeubank.github.io/tdm-gcc/download/) 64-bit compiler suite installed. It builds all the collectors and corresponding YAML configuration files into %GOPATH%/bin

**Comment by Kohinor46** [comment]
I try to build it on macos for using on windows. Is it possibly?

**Comment by ibmmqmet** [comment]
See #47 for some discussion on cross-compiling code. Someone has managed to compile on Linux for execution on Windows. But it's not something I have tested myself - I always compile on the native platform.

**Comment by Kohinor46** [comment]
Now when i try:
`go build -o $GOPATH/bin/mq_influx ./cmd/mq_influx/*.go`
it return to me error:
`C:\Users\*****\go\src\mq-metric-samples> go build -o %GOPATH%/bin/mq_influx ./cmd/mq_influx/*.go
go: github.com/aws/aws-sdk-go@v1.30.18: Get "https://proxy.golang.org/github.com/aws/aws-sdk-go/@v/v1.30.18.mod": dial tcp: lookup proxy.golang.org: no such host
 
C:\Users\*****\go\src\mq-metric-samples>echo %GOPATH%
C:\Users\*****\go`
Why it aws packet if i try to influx?

**Comment by liz72703** [comment]
I have the same issue when I try to build the prometheus code on Rhel.  

[mqm@ls-ibmib01-dev mq-metric-samples-5.1.3]$ go build -o $GOPATH/bin/mq_prometheus ./cmd/mq_prometheus/*.go

go: github.com/aws/aws-sdk-go@v1.30.18: Get "https://proxy.golang.org/github.com/aws/aws-sdk-go/@v/v1.30.18.mod": dial tcp 142.250.113.141:443: i/o timeout

**Comment by ibmmqmet** [comment]
The `go.mod` file in the root of the repo refers to all the client libraries needed across all the collectors, hence a reference to the aws library. Biut everything is already in the `vendor` tree so no downloads should be necessary. Use `go build -mod=vendor ...` to use the pre-populated tree.

**Comment by liz72703** [comment]
Thank you, Mark!  I knew everything was in the vendor tree, just didn't understand why it wasn't using it.  Admittedly, I haven't used Go much.  Appreciate the tip!

Liz
