### ISSUE TITLE
Error when i try to run multiple agent on the same server 

### ISSUE THREAD

**Issue by abenbouz** [ibm-messaging/mq-metric-samples#57]
hello ,
i have 10 queue manager running on the same server 
i'm using the mq-metric-samples version 5.1.2 and even tried with version 5.1.3
and when i try to run the metrics agent it's failing for a lot of them  with bellow error :

goroutine 0 [idle]:
runtime: unknown pc 0x7fa33737d387
stack: frame={sp:0x7f9fd80fd918, fp:0x0} stack=[0x7f9fc01fe268,0x7f9fd80fde68)
00007f9fd80fd818:  ffffffffffffff00  000000c000332300 
00007f9fd80fd828:  000000c00035d3e0  000000c0003826c0 
00007f9fd80fd838:  000000c00036fc00  000000c0003834a0 
00007f9fd80fd848:  000000c000383560  000000c0003834d0 
00007f9fd80fd858:  000000c000383590  00007f9fd80fd940 
00007f9fd80fd868:  0000000000000007  0000000000000001 
00007f9fd80fd878:  0000000000000000  0000000000000007 
00007f9fd80fd888:  00007fa337378976  0000000000000000 
00007f9fd80fd898:  00007f9fd80fda30  00007f9fbc000b00 
00007f9fd80fd8a8:  00007f9f00000001  0000000000000001 
00007f9fd80fd8b8:  000000c0001d3fb0  0000000000000002 
00007f9fd80fd8c8:  0000000000000000  0000000000000000 
00007f9fd80fd8d8:  0000000000000000  0000000000000000 
00007f9fd80fd8e8:  00007fa33770f868  0000000000ab9f5d 
00007f9fd80fd8f8:  00007f9fbc0008c0  0000000000000000 
00007f9fd80fd908:  0000000000a677f0  0000000000000000 
00007f9fd80fd918: <00007fa33737ea78  0000000000000020 
00007f9fd80fd928:  0000000000000000  0000000000000000 
00007f9fd80fd938:  0000000000000000  0000000000000000 
00007f9fd80fd948:  0000000000000000  0000000000000000 
00007f9fd80fd958:  0000000000000000  0000000000000000 
00007f9fd80fd968:  0000000000000000  0000000000000000 
00007f9fd80fd978:  0000000000000000  0000000000000000 
00007f9fd80fd988:  0000000000000000  0000000000000000 
00007f9fd80fd998:  0000000000000000  0000000000000000 
00007f9fd80fd9a8:  0000000000000000  0000000000000000 
00007f9fd80fd9b8:  0000000000000000  0000000000000000 
00007f9fd80fd9c8:  0000000000000000  0000000000000000 
00007f9fd80fd9d8:  0000000000000000  0000000000000000 
00007f9fd80fd9e8:  0000000000000000  0000000000000000 
00007f9fd80fd9f8:  0000000000000000  00007f9fbc0008c0 
00007f9fd80fda08:  0000000000000000  0000000000a677f0 
runtime: unknown pc 0x7fa33737d387
stack: frame={sp:0x7f9fd80fd918, fp:0x0} stack=[0x7f9fc01fe268,0x7f9fd80fde68)
00007f9fd80fd818:  ffffffffffffff00  000000c000332300 
00007f9fd80fd828:  000000c00035d3e0  000000c0003826c0 
00007f9fd80fd838:  000000c00036fc00  000000c0003834a0 
00007f9fd80fd848:  000000c000383560  000000c0003834d0 
00007f9fd80fd858:  000000c000383590  00007f9fd80fd940 
00007f9fd80fd868:  0000000000000007  0000000000000001 
00007f9fd80fd878:  0000000000000000  0000000000000007 
00007f9fd80fd888:  00007fa337378976  0000000000000000 
00007f9fd80fd898:  00007f9fd80fda30  00007f9fbc000b00 
00007f9fd80fd8a8:  00007f9f00000001  0000000000000001 
00007f9fd80fd8b8:  000000c0001d3fb0  0000000000000002 
00007f9fd80fd8c8:  0000000000000000  0000000000000000 
00007f9fd80fd8d8:  0000000000000000  0000000000000000 
00007f9fd80fd8e8:  00007fa33770f868  0000000000ab9f5d 
00007f9fd80fd8f8:  00007f9fbc0008c0  0000000000000000 
00007f9fd80fd908:  0000000000a677f0  0000000000000000 
00007f9fd80fd918: <00007fa33737ea78  0000000000000020 
00007f9fd80fd928:  0000000000000000  0000000000000000 
00007f9fd80fd938:  0000000000000000  0000000000000000 
00007f9fd80fd948:  0000000000000000  0000000000000000 
00007f9fd80fd958:  0000000000000000  0000000000000000 
00007f9fd80fd968:  0000000000000000  0000000000000000 
00007f9fd80fd978:  0000000000000000  0000000000000000 
00007f9fd80fd988:  0000000000000000  0000000000000000 
00007f9fd80fd998:  0000000000000000  0000000000000000 
00007f9fd80fd9a8:  0000000000000000  0000000000000000 
00007f9fd80fd9b8:  0000000000000000  0000000000000000 
00007f9fd80fd9c8:  0000000000000000  0000000000000000 
00007f9fd80fd9d8:  0000000000000000  0000000000000000 
00007f9fd80fd9e8:  0000000000000000  0000000000000000 
00007f9fd80fd9f8:  0000000000000000  00007f9fbc0008c0 
00007f9fd80fda08:  0000000000000000  0000000000a677f0 

goroutine 1 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x7fa2c70ecee8, 0x72, 0x0)
	/data/mqm/tools/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0003e4b18, 0x72, 0x0, 0x0, 0x9bbdc8)
	/data/mqm/tools/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/data/mqm/tools/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0003e4b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/mqm/tools/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc0003e4b00, 0xaaa77941f4eddf01, 0xc0003ecc80, 0xaaa77941f4eddf26)
	/data/mqm/tools/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0003f09a0, 0x600e9c11, 0xc000143ca0, 0x4c0ee6)
	/data/mqm/tools/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0003f09a0, 0xc000143cf0, 0x18, 0xc000000180, 0x83841c)
	/data/mqm/tools/go/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc000422000, 0xa80660, 0xc0003f09a0, 0x0, 0x0)
	/data/mqm/tools/go/src/net/http/server.go:2930 +0x25d
net/http.(*Server).ListenAndServe(0xc000422000, 0xc000422000, 0xc000143f30)
	/data/mqm/tools/go/src/net/http/server.go:2859 +0xb7
net/http.ListenAndServe(...)
	/data/mqm/tools/go/src/net/http/server.go:3115
main.main()
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/cmd/mq_prometheus/main.go:119 +0x523

goroutine 38 [select]:
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc000110870, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:510 +0xb6a
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x7fa2c5f146b8, 0xc0003d40a0, 0xc0001b9300)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:126 +0x93
net/http.HandlerFunc.ServeHTTP(0xc0003dbb20, 0x7fa2c5f146b8, 0xc0003d40a0, 0xc0001b9300)
	/data/mqm/tools/go/src/net/http/server.go:2041 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7fa2c5f146b8, 0xc0003d40a0, 0xc0001b9300)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:40 +0xab
net/http.HandlerFunc.ServeHTTP(0xc0003e1a10, 0x7fa2c5f146b8, 0xc0003d40a0, 0xc0001b9300)
	/data/mqm/tools/go/src/net/http/server.go:2041 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0xa80920, 0xc0004220e0, 0xc0001b9300)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:100 +0xda
net/http.HandlerFunc.ServeHTTP(0xc0003e1b00, 0xa80920, 0xc0004220e0, 0xc0001b9300)
	/data/mqm/tools/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0x105f3c0, 0xa80920, 0xc0004220e0, 0xc0001b9300)
	/data/mqm/tools/go/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc000422000, 0xa80920, 0xc0004220e0, 0xc0001b9300)
	/data/mqm/tools/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0003585a0, 0xa81ce0, 0xc0003ee680)
	/data/mqm/tools/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/data/mqm/tools/go/src/net/http/server.go:2962 +0x35c

goroutine 76 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7fa2c70ece08, 0x72, 0xffffffffffffffff)
	/data/mqm/tools/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0003e4b98, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/data/mqm/tools/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/data/mqm/tools/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0003e4b80, 0xc00044e401, 0x1, 0x1, 0x0, 0x0, 0x0)
	/data/mqm/tools/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0003e4b80, 0xc00044e401, 0x1, 0x1, 0x0, 0x0, 0x0)
	/data/mqm/tools/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0003189d8, 0xc00044e401, 0x1, 0x1, 0x0, 0x0, 0x0)
	/data/mqm/tools/go/src/net/net.go:184 +0x8e
net/http.(*connReader).backgroundRead(0xc00044e3f0)
	/data/mqm/tools/go/src/net/http/server.go:689 +0x58
created by net/http.(*connReader).startBackgroundRead
	/data/mqm/tools/go/src/net/http/server.go:685 +0xd0

goroutine 78 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc0005ac088)
	/data/mqm/tools/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0005ac080)
	/data/mqm/tools/go/src/sync/waitgroup.go:130 +0x64
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc0005ac080, 0xc0003e2060, 0xc0003e20c0)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:460 +0x2b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:459 +0x5d8

goroutine 79 [semacquire]:
github.com/prometheus/client_golang/prometheus.NewGaugeVec.func1(0xc000e16500, 0x8, 0x8, 0x0, 0x0)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/gauge.go:152 +0xae
github.com/prometheus/client_golang/prometheus.(*metricMap).getOrCreateMetricWithLabels(0xc0003dd860, 0x1533ebd37670bb8b, 0xc000e81110, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/vec.go:356 +0x231
github.com/prometheus/client_golang/prometheus.(*metricVec).getMetricWith(0xc0003dd830, 0xc000e81110, 0x20, 0xb2d8d8441a7f0476, 0x20, 0xc0000dfef8)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/vec.go:154 +0xa4
github.com/prometheus/client_golang/prometheus.(*GaugeVec).GetMetricWith(...)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/gauge.go:203
github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(0xc000318818, 0xc000e81110, 0x9bbea8, 0x7)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/gauge.go:226 +0x3c
main.(*exporter).Collect(0xc0003e2a80, 0xc0003e2060)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/cmd/mq_prometheus/exporter.go:343 +0x1f86
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:443 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:535 +0xe36

rax    0x0
rbx    0x7fa33770f868
rcx    0xffffffffffffffff
rdx    0x6
rdi    0xf26d
rsi    0xf87d
rbp    0xab9f5d
rsp    0x7f9fd80fd918
r8     0xa
r9     0x7f9fd80fe700
r10    0x8
r11    0x202
r12    0x7f9fbc0008c0
r13    0x0
r14    0xa677f0
r15    0x0
rip    0x7fa33737d387
rflags 0x202
cs     0x33
fs     0x0
gs     0x0

have you any idea about the problem ?

Thanks

**Comment by abenbouz** [comment]
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fa15ccf1387 m=3 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fa15ccf1387
stack: frame={sp:0x7fa11c89c908, fp:0x0} stack=[0x7fa10499d268,0x7fa11c89ce68)
00007fa11c89c808:  2000202000000000  ffffffffffffffff 
00007fa11c89c818:  ffffffff000000ff  000000c000426b10 
00007fa11c89c828:  000000c000427650  000000c00042eed0 
00007fa11c89c838:  000000c00042f290  000000c00042fbf0 
00007fa11c89c848:  000000c000436ed0  000000c000437650 
00007fa11c89c858:  000000c000451290  0000000000000001 
00007fa11c89c868:  0000000000000000  0000000000000007 
00007fa11c89c878:  00007fa15ccec976  0000000000000000 
00007fa11c89c888:  00007fa11c89ca20  00007fa0e8002970 
00007fa11c89c898:  00007fa100000001  0000000000000001 
00007fa11c89c8a8:  000000c000427650  00007fa11c89c940 
00007fa11c89c8b8:  000000c00042f290  0000000000000002 
00007fa11c89c8c8:  0000000000000000  0000000000000000 
00007fa11c89c8d8:  00007fa15d083868  0000000000ab9f5d 
00007fa11c89c8e8:  00007fa0e80008c0  0000000000000000 
00007fa11c89c8f8:  0000000000a677f0  0000000000000000 
00007fa11c89c908: <00007fa15ccf2a78  0000000000000020 
00007fa11c89c918:  0000000000000000  0000000000000000 
00007fa11c89c928:  0000000000000000  0000000000000000 
00007fa11c89c938:  0000000000000000  0000000000000000 
00007fa11c89c948:  0000000000000000  0000000000000000 
00007fa11c89c958:  0000000000000000  0000000000000000 
00007fa11c89c968:  0000000000000000  0000000000000000 
00007fa11c89c978:  0000000000000000  0000000000000000 
00007fa11c89c988:  0000000000000000  0000000000000000 
00007fa11c89c998:  0000000000000000  0000000000000000 
00007fa11c89c9a8:  0000000000000000  0000000000000000 
00007fa11c89c9b8:  0000000000000000  0000000000000000 
00007fa11c89c9c8:  0000000000000000  0000000000000000 
00007fa11c89c9d8:  0000000000000000  0000000000000000 
00007fa11c89c9e8:  0000000000000000  0000000000000000 
00007fa11c89c9f8:  0000000000000000  0000000000a677f0 
runtime: unknown pc 0x7fa15ccf1387
stack: frame={sp:0x7fa11c89c908, fp:0x0} stack=[0x7fa10499d268,0x7fa11c89ce68)
00007fa11c89c808:  2000202000000000  ffffffffffffffff 
00007fa11c89c818:  ffffffff000000ff  000000c000426b10 
00007fa11c89c828:  000000c000427650  000000c00042eed0 
00007fa11c89c838:  000000c00042f290  000000c00042fbf0 
00007fa11c89c848:  000000c000436ed0  000000c000437650 
00007fa11c89c858:  000000c000451290  0000000000000001 
00007fa11c89c868:  0000000000000000  0000000000000007 
00007fa11c89c878:  00007fa15ccec976  0000000000000000 
00007fa11c89c888:  00007fa11c89ca20  00007fa0e8002970 
00007fa11c89c898:  00007fa100000001  0000000000000001 
00007fa11c89c8a8:  000000c000427650  00007fa11c89c940 
00007fa11c89c8b8:  000000c00042f290  0000000000000002 
00007fa11c89c8c8:  0000000000000000  0000000000000000 
00007fa11c89c8d8:  00007fa15d083868  0000000000ab9f5d 
00007fa11c89c8e8:  00007fa0e80008c0  0000000000000000 
00007fa11c89c8f8:  0000000000a677f0  0000000000000000 
00007fa11c89c908: <00007fa15ccf2a78  0000000000000020 
00007fa11c89c918:  0000000000000000  0000000000000000 
00007fa11c89c928:  0000000000000000  0000000000000000 
00007fa11c89c938:  0000000000000000  0000000000000000 
00007fa11c89c948:  0000000000000000  0000000000000000 
00007fa11c89c958:  0000000000000000  0000000000000000 
00007fa11c89c968:  0000000000000000  0000000000000000 
00007fa11c89c978:  0000000000000000  0000000000000000 
00007fa11c89c988:  0000000000000000  0000000000000000 
00007fa11c89c998:  0000000000000000  0000000000000000 
00007fa11c89c9a8:  0000000000000000  0000000000000000 
00007fa11c89c9b8:  0000000000000000  0000000000000000 
00007fa11c89c9c8:  0000000000000000  0000000000000000 
00007fa11c89c9d8:  0000000000000000  0000000000000000 
00007fa11c89c9e8:  0000000000000000  0000000000000000 
00007fa11c89c9f8:  0000000000000000  0000000000a677f0 

goroutine 1 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7fa0eca60ee8, 0x72, 0x0)
	/data/mqm/tools/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0002c0718, 0x72, 0x0, 0x0, 0x9bbdc8)
	/data/mqm/tools/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/data/mqm/tools/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0002c0700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/mqm/tools/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc0002c0700, 0x62a3a50d51bb0c01, 0xc000324a50, 0x62a3a50d51bb0c53)
	/data/mqm/tools/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00030b560, 0x600ec350, 0xc000143ca0, 0x4c0ee6)
	/data/mqm/tools/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00030b560, 0xc000143cf0, 0x18, 0xc000000180, 0x83841c)
	/data/mqm/tools/go/src/net/tcpsock.go:261 +0x64
net/http.(*Server).Serve(0xc0002a60e0, 0xa80660, 0xc00030b560, 0x0, 0x0)
	/data/mqm/tools/go/src/net/http/server.go:2930 +0x25d
net/http.(*Server).ListenAndServe(0xc0002a60e0, 0xc0002a60e0, 0xc000143f30)
	/data/mqm/tools/go/src/net/http/server.go:2859 +0xb7
net/http.ListenAndServe(...)
	/data/mqm/tools/go/src/net/http/server.go:3115
main.main()
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/cmd/mq_prometheus/main.go:119 +0x523

goroutine 121 [semacquire]:
github.com/ibm-messaging/mq-golang/v5/mqmetric.traceExitF(0x9bee7f, 0xc, 0x0, 0x9bbbd0, 0x7, 0xc00036ae20, 0x1, 0x1)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/log.go:124 +0x1f3
github.com/ibm-messaging/mq-golang/v5/mqmetric.parseChlData(0xc0000003f3, 0xc000524fc0, 0xc000b38824, 0x47c, 0x27dc, 0x0, 0x0)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:461 +0x104c
github.com/ibm-messaging/mq-golang/v5/mqmetric.collectChannelStatus(0x7ffd9fce63ce, 0x1, 0x7ffd000003f3, 0x1, 0x0)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:326 +0x469
github.com/ibm-messaging/mq-golang/v5/mqmetric.CollectChannelStatus(0x7ffd9fce63ce, 0x1, 0x9bb56e, 0x5)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/channel.go:218 +0xcdb
main.(*exporter).Collect(0xc0003cc4e0, 0xc000280060)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/cmd/mq_prometheus/exporter.go:199 +0x5295
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:443 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:535 +0xe36

goroutine 37 [select, 1 minutes]:
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc000110870, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:510 +0xb6a
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x7fa0eca20288, 0xc0003b1310, 0xc0006a4000)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:126 +0x93
net/http.HandlerFunc.ServeHTTP(0xc000328e00, 0x7fa0eca20288, 0xc0003b1310, 0xc0006a4000)
	/data/mqm/tools/go/src/net/http/server.go:2041 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7fa0eca20288, 0xc0003b1310, 0xc0006a4000)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:40 +0xab
net/http.HandlerFunc.ServeHTTP(0xc00031fda0, 0x7fa0eca20288, 0xc0003b1310, 0xc0006a4000)
	/data/mqm/tools/go/src/net/http/server.go:2041 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0xa80920, 0xc0002a61c0, 0xc0006a4000)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go:100 +0xda
net/http.HandlerFunc.ServeHTTP(0xc00031fe90, 0xa80920, 0xc0002a61c0, 0xc0006a4000)
	/data/mqm/tools/go/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0x105f3c0, 0xa80920, 0xc0002a61c0, 0xc0006a4000)
	/data/mqm/tools/go/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0002a60e0, 0xa80920, 0xc0002a61c0, 0xc0006a4000)
	/data/mqm/tools/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000326d20, 0xa81ce0, 0xc0002a10c0)
	/data/mqm/tools/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/data/mqm/tools/go/src/net/http/server.go:2962 +0x35c

goroutine 132 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7fa0eca60e08, 0x72, 0xffffffffffffffff)
	/data/mqm/tools/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0002c0798, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/data/mqm/tools/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/data/mqm/tools/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002c0780, 0xc000362791, 0x1, 0x1, 0x0, 0x0, 0x0)
	/data/mqm/tools/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0002c0780, 0xc000362791, 0x1, 0x1, 0x1065170, 0x1065160, 0xc000602778)
	/data/mqm/tools/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00028e908, 0xc000362791, 0x1, 0x1, 0x0, 0x0, 0x0)
	/data/mqm/tools/go/src/net/net.go:184 +0x8e
net/http.(*connReader).backgroundRead(0xc000362780)
	/data/mqm/tools/go/src/net/http/server.go:689 +0x58
created by net/http.(*connReader).startBackgroundRead
	/data/mqm/tools/go/src/net/http/server.go:685 +0xd0

goroutine 134 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc0002d4028)
	/data/mqm/tools/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0002d4020)
	/data/mqm/tools/go/src/sync/waitgroup.go:130 +0x64
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc0002d4020, 0xc000280060, 0xc0002800c0)
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:460 +0x2b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/data/mqm/tools/mq_prometheus_exporter/src/mq-metric-samples-5.1.3/vendor/github.com/prometheus/client_golang/prometheus/registry.go:459 +0x5d8

rax    0x0
rbx    0x7fa15d083868
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x3bdc
rsi    0x3c36
rbp    0xab9f5d
rsp    0x7fa11c89c908
r8     0xa
r9     0x7fa11c89d700
r10    0x8
r11    0x202
r12    0x7fa0e80008c0
r13    0x0
r14    0xa677f0
r15    0x0
rip    0x7fa15ccf1387
rflags 0x202
cs     0x33
fs     0x0
gs     0x0

**Comment by ibmmqmet** [comment]
The line  `pthread_create failed: Resource temporarily unavailable` looks like one or more of your kernel resources or ulimit setting is not large enough. 

10 queue managers on a box is larger than the mqconfig command would expect to generate recommended values for - it's not inherently a problem but you do need to size appropriately.

**Comment by abenbouz** [comment]
hello Mark ,
ok thanks much for your answer 
In fact you are right i'm looking for tuning system resources for that .
thanks i'm closing the issue
