### ISSUE TITLE
Error in Channel.go while compiling 

### ISSUE THREAD

**Issue by nikhilsuryan** [ibm-messaging/mq-metric-samples#6]
Using the Merged master code base:

mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric/channel.go:312:25: multiple-value regexp.MatchString() in single-value context
mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/mqmetric/channel.go:312:26: undefined: subkey

**Comment by ibmmqmet** [comment]
Oops - dep was not pulling in the right tree. Should be fixed now.

**Comment by nikhilsuryan** [comment]
Thanks for quick response @ibmmqmet, its is fixed now.
