### ISSUE TITLE
docs link

### ISSUE THREAD

**Issue by wirowka** [ibm-messaging/mq-metric-samples#60]
hi
Please kindly check the links provided to the documentation of the metrics, one of them does not work.
Thanks in advance 
Best Regards

**Comment by ibmmqmet** [comment]
"one of them does not work."

Might help if you gave a clue.

**Comment by wirowka** [comment]
https://www.ibm.com/developerworks/community/blogs/messaging/entry/Statistics_published_to_the_system_topic_in_MQ_v9?lang=en
