### ISSUE TITLE
Performance overhead

### ISSUE THREAD

**Issue by a359089** [ibm-messaging/mq-metric-samples#62]
Any rough estimate on the performance penalty while metrics are collected for dozens of queues with persistence messages? Better, any plans to include this with MQ performance harness ( http://ibm-messaging.github.io/mqperf/ ) ?

**Comment by ibmmqmet** [comment]
Whether a queue has persistent messages or not is irrelevant. All the queries and publications here are made with NP messages; the type and number of messages on a queue do not affect the collections. 

There's been no performance measurement of the cost of collecting these metrics that I know of.

**Comment by stmassey** [comment]
When you refer to the MQ Performance harness, I'm assuming you mean cph (https://github.com/ibm-messaging/mq-cph). Which metrics would be useful? In the requester-responder scenarios featured in the performance reports, the queue depths are limited by the number of requester applications (each thread waits for its own response).
