### ISSUE TITLE
Channel Metrics with MQ 9.2.1

### ISSUE THREAD

**Issue by mrkfordev** [ibm-messaging/mq-metric-samples#66]
Hello, 

Is there any problems reported on channel metrics with MQ v9.2.1.0? 
I see the queue metrics, manager queue metrics but not channel metrics :/

**Comment by ibmmqmet** [comment]
More information needed.

Have you configured which channels are monitored? What metric names are you looking for? What collector are you using?

**Comment by mrkfordev** [comment]
I tested the monitoring with : set channels=
-ibmmq.monitoredChannels="!SYSTEM.*" and -ibmmq.monitoredChannels="*"

I used the MQ_Prometheus collector on windows. 

I need at least the status of the channel or more if possible, except that no metrics are reported.

**Comment by ibmmqmet** [comment]
It would help if you gave the COMPLETE configuration.  Setting loglevel to DEBUG will dump the applied config. I suspect, though, since you appear to be using command line flags rather than the yaml config approach, that you have not additionally set the flag to say to enable object status commands `- ibmmq.qStatus=true` or `-ibmmq.useStatus=true`

**Comment by mrkfordev** [comment]
Still no result even with these two flags. The only metric that came back is: ibmmq_qmgr_channel_initiator_status

Here is the command I use: 
`
@echo off
set qMgr=%1
set MQPROMPORT=%2

set queues="!SYSTEM.*,!AMQ.*"
set channels="*"

C:\Gowork\bin\mq_prometheus_win.exe -ibmmq.queueManager=%qMgr% -ibmmq.monitoredQueues="%queues%" -ibmmq.monitoredChannels="%channels%" -log.level=debug -ibmmq.httpListenPort=%MQPROMPORT% -ibmmq.useStatus=true
`

Please find attached the log file. 
[mq.prometheus.log](https://github.com/ibm-messaging/mq-metric-samples/files/6343544/mq.prometheus.log)


I can see that channel metrics are created. But the channel metrics are not found in prometheus.

**Comment by ibmmqmet** [comment]
That log is not showing any requests at all for metric collection from prometheus. After the "listening on http address" there should be more lines on each poll interval to show that the data is being pulled. So maybe you've not waited long enough. You also have `ShowInactiveChannels:false` so you would only see metrics for channels that are actually running.

**Comment by mrkfordev** [comment]
1. Please find below the update of the logs with the more data 
[mq.prometheus.log](https://github.com/ibm-messaging/mq-metric-samples/files/6344606/mq.prometheus.log)


2. How can we set ShowInactiveChannels to true? Which flag is it? 

3. Prometheus does not see the channel metrics. They are not even proposed like the others.

**Comment by mrkfordev** [comment]
any suggestions please ???

**Comment by ibmmqmet** [comment]
thanks for the update to confirm solution
