### ISSUE TITLE
Queueing in blocks possible?

### ISSUE THREAD

**Issue by OlafKocanda** [ibm-messaging/mq-metric-samples#68]
Hi there,

thanks for this exporter, it really helps us.

Is there a possibility in the [config.common.yaml](https://github.com/ibm-messaging/mq-metric-samples/blob/master/config.common.yaml) considered, to collect the queues in blocks? We are looking for a way to deal with [MAXHANDS](https://www.ibm.com/support/pages/maxhands-queue-manager-parameter) without changing it.

In your case it would be e.g. to first collect
- "!SYSTEM.*"

and thereafter
 - "!AMQ.*"

Thanks in advance!

**Comment by ibmmqmet** [comment]
Unfortunately not.

Status queries (the equivalent of DISPLAY xxSTATUS commands) can be made using wildcards, where all the patterns are inclusive (no `!` options). 

But the queue metrics that are published require individual subscriptions. This is a queue manager limitation.

**Comment by ibmmqmet** [comment]
closing as answered
