### ISSUE TITLE
Variables MQCD_LENGTH_11, MQCD_VERSION_11, MQ_CERT_LABEL_LENGTH

### ISSUE THREAD

**Issue by oselimzhanov** [ibm-messaging/mq-metric-samples#70]
Hello!
Today, on one of our test environments, while trying building a component for MQ (https://github.com/ibm-messaging/mq-metric-samples#building-a-component),
we faced with error like this:

"
# github.com/ibm-messaging/mq-golang/v5/ibmmq
/go/pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.2.0/ibmmq/mqiMQCD.go:154:21: could not determine kind of name for C.MQCD_LENGTH_11
/go/pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.2.0/ibmmq/mqiMQCD.go:112:17: could not determine kind of name for C.MQCD_VERSION_11
/go/pkg/mod/github.com/ibm-messaging/mq-golang/v5@v5.2.0/ibmmq/mqiMQCD.go:206:76: could not determine kind of name for C.MQ_CERT_LABEL_LENGTH
"

Preliminary googling did not bring accurate results

Please provide advice on what values ​​should be assigned to the variables MQCD_LENGTH_11, MQCD_VERSION_11, MQ_CERT_LABEL_LENGTH

Thank you in advance!

**Comment by ibmmqmet** [comment]
You must be trying to build against a very old version of the prereq MQ client libraries - those constants are defined in the MQ V8 header files.

**Comment by oselimzhanov** [comment]
Hi!


new libraries already present in the system


(lucky)root=> / # lslpp -L | grep mqm
  mqm.base.runtime           7.5.0.7    C     F    IBM WebSphere MQ Runtime for
  mqm.base.samples           7.5.0.7    C     F    IBM WebSphere MQ Samples
  mqm.base.sdk               7.5.0.7    C     F    IBM WebSphere MQ Base Kit for
  mqm.client.rte             7.5.0.7    C     F    IBM WebSphere MQ Client for
  mqm.gskit.rte              7.5.0.7    C     F    IBM Global Security Kit for
  mqm.java.rte               7.5.0.7    C     F    IBM WebSphere MQ Java Client,
  mqm.jre.rte                7.5.0.7    C     F    IBM WebSphere MQ Java Runtime
  mqm.man.en_US.data         7.5.0.7    C     F    IBM WebSphere MQ Man Pages -
  mqm.server.rte             7.5.0.7    C     F    IBM WebSphere MQ Server
  mqm.xr.clients             7.5.0.7    C     F    IBM WebSphere MQ Telemetry
  mqm.xr.service             7.5.0.7    C     F    IBM WebSphere MQ Telemetry
  
  
  
  (lucky)root=> / # lslpp -R ALL -L | grep mqm
INSTALL ROOT PATH  = /usr/mqm9
  mqm.amqp.rte               9.0.4.0    C     F    IBM MQ AMQP Service
  mqm.base.runtime           9.0.4.0    C     F    IBM MQ Runtime for Client and
  mqm.base.samples           9.0.4.0    C     F    IBM MQ Samples
  mqm.base.sdk               9.0.4.0    C     F    IBM MQ Base Kit for Client and
  mqm.client.rte             9.0.4.0    C     F    IBM MQ Client for AIX
  mqm.gskit.rte              9.0.4.0    C     F    IBM Global Security Kit for
  mqm.java.rte               9.0.4.0    C     F    IBM MQ Java Client, JMS and
  mqm.jre.rte                9.0.4.0    C     F    IBM MQ Java Runtime
  mqm.man.en_US.data         9.0.4.0    C     F    IBM MQ Man Pages - U.S.
  mqm.msg.en_US              9.0.4.0    C     F    IBM MQ Messages - U.S. English
  mqm.server.rte             9.0.4.0    C     F    IBM MQ Server
  mqm.web.rte                9.0.4.0    C     F    IBM MQ REST API and Console
  mqm.base.runtime           7.5.0.7    C     F    IBM WebSphere MQ Runtime for
  mqm.base.samples           7.5.0.7    C     F    IBM WebSphere MQ Samples
  mqm.base.sdk               7.5.0.7    C     F    IBM WebSphere MQ Base Kit for
  mqm.client.rte             7.5.0.7    C     F    IBM WebSphere MQ Client for
  mqm.gskit.rte              7.5.0.7    C     F    IBM Global Security Kit for
  mqm.java.rte               7.5.0.7    C     F    IBM WebSphere MQ Java Client,
  mqm.jre.rte                7.5.0.7    C     F    IBM WebSphere MQ Java Runtime
  mqm.man.en_US.data         7.5.0.7    C     F    IBM WebSphere MQ Man Pages -
  mqm.server.rte             7.5.0.7    C     F    IBM WebSphere MQ Server
  mqm.xr.clients             7.5.0.7    C     F    IBM WebSphere MQ Telemetry
  mqm.xr.service             7.5.0.7    C     F    IBM WebSphere MQ Telemetry
  
  
  
 How to specify an alternative ROOT PATH for the go-compiler?

**Comment by ibmmqmet** [comment]
You should be able to set CGO_CFLAGS and CGO_LDFLAGS environment variables.

**Comment by oselimzhanov** [comment]
Hi

work fine with settings:


(lucky)root=> ibm-mq-exporter # echo -e "LIBPATH $LIBPATH\nPATH $PATH\nGOROOT $GOROOT\nCGO_CFLAGS $CGO_CFLAGS\nMQ_INSTALLATION_PATH $MQ_INSTALLATION_PATH\nCGO_LDFLAGS_ALLOW $CGO_LDFLAGS_ALL
OW"
LIBPATH /opt/freeware/lib:/usr/lib:/opt/freeware/lib/golang/bin:/opt/freeware/lib/golang:/opt/freeware/lib/golang/lib
PATH /usr/lib:/opt/freeware/lib:/usr/lib:/opt/freeware/lib/golang/bin:/usr/mqm9/usr/mqm/inc:/usr/linux/sbin:/usr/krb5/bin:/usr/krb5/sbin:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/usr/java8_64/jre/bin:/usr/java8_64/bin:/usr/local/bin:/opt/freeware/sbin:/opt/freeware/bin:/usr/DynamicLinkManager/bin:/usr/lpp/mmfs/bin
GOROOT
CGO_CFLAGS -I/usr/mqm9/usr/mqm/inc
MQ_INSTALLATION_PATH /usr/mqm9/usr/mqm
CGO_LDFLAGS_ALLOW -Wl,-rpath.*



Thanks for your help Mark.
