### ISSUE TITLE
FATA [0000] Cannot connect to queue manager

### ISSUE THREAD

**Issue by oselimzhanov** [ibm-messaging/mq-metric-samples#71]
Hello!

I'm trying to connect to an unencrypted channel to collect metrics using mq_prometheus:
/usr/local/bin/mq_prometheus -ibmmq.channel=CHANNEL1 -ibmmq.userid=user -ibmmq.password=<password> -ibmmq.queueManager=MQMQGR9 -log.level string=debug

  and I get the error:
FATA [0000] Cannot connect to queue manager MQMQGR9: MQCONNX: MQCC=MQCC_FAILED [2] MQRC=MQRC_CD_ERROR [2277]

How can I understand why the queue manager did not accept connections from the mq_prometheus exporter?
Why  I can't see any mention of this event in the /var/mqm/qmgrs/MQMQGR9/errors/AMQERR0*.LOG logs?

Please provide your recommendations for writing a custom connection string
Thanks in advance!

--------------------------
dspmq -m MQMQGR9 -o all
QMNAME(MQMQGR9) STATUS(Running) DEFAULT(no) STANDBY(Not permitted) INSTNAME(Installation2) INSTPATH(/usr/mqm9/usr/mqm) INSTVER(9.0.4.0)

-------------------------

runmqsc MQMQGR9
5724-H72 (C) Copyright IBM Corp. 1994, 2017.
Starting MQSC for queue manager MQMQGR9.

DISPLAY QMGR
     1 : DISPLAY QMGR
AMQ8408I: Display Queue Manager details.
   QMNAME(MQMQGR9)                    ACCTCONO(DISABLED)
   ACCTINT(1800)                           ACCTMQI(OFF)
   ACCTQ(OFF)                              ACTIVREC(MSG)
   ACTVCONO(DISABLED)                      ACTVTRC(OFF)
   ALTDATE(2020-10-28)                     ALTTIME(13.00.32)
   AMQPCAP(YES)                            AUTHOREV(DISABLED)
   CCSID(1208)                             CERTLABL(ibmwebspheremqMQMQGR9)
   CERTVPOL(ANY)                           CHAD(DISABLED)
   CHADEV(DISABLED)                        CHADEXIT( )
   CHLEV(DISABLED)                         CHLAUTH(DISABLED)
   CLWLDATA( )                             CLWLEXIT( )
   CLWLLEN(100)                            CLWLMRUC(999999999)
   CLWLUSEQ(LOCAL)                         CMDEV(DISABLED)
   CMDLEVEL(904)                           COMMANDQ(SYSTEM.ADMIN.COMMAND.QUEUE)
   CONFIGEV(DISABLED)
   CONNAUTH(SYSTEM.DEFAULT.AUTHINFO.IDPWLDAP)
   CRDATE(2019-05-22)                      CRTIME(09.10.04)
   CUSTOM( )                               DEADQ(MQMQGR9.DLQ)
   DEFCLXQ(SCTQ)                           DEFXMITQ( )
   DESCR( )                                DISTL(YES)
   IMGINTVL(60)                            IMGLOGLN(OFF)
   IMGRCOVO(YES)                           IMGRCOVQ(YES)
   IMGSCHED(MANUAL)                        INHIBTEV(DISABLED)
   IPADDRV(IPV4)                           LOCALEV(DISABLED)
   LOGGEREV(DISABLED)                      MARKINT(5000)
   MAXHANDS(256)                           MAXMSGL(104857600)
   MAXPROPL(NOLIMIT)                       MAXPRTY(9)
   MAXUMSGS(10000)                         MONACLS(QMGR)
   MONCHL(OFF)                             MONQ(MEDIUM)
   PARENT( )                               PERFMEV(DISABLED)
   PLATFORM(UNIX)                          PSMODE(ENABLED)
   PSCLUS(ENABLED)                         PSNPMSG(DISCARD)
   PSNPRES(NORMAL)                         PSRTYCNT(5)
   PSSYNCPT(IFPER)
   QMID(MQMQGR9_2019-05-22_09.10.04)
   REMOTEEV(DISABLED)                      REPOS( )
   REPOSNL( )                              REVDNS(ENABLED)
   ROUTEREC(MSG)                           SCHINIT(QMGR)
   SCMDSERV(QMGR)                          SPLCAP(DISABLED)
   SSLCRLNL( )                             SSLCRYP( )
   SSLEV(DISABLED)                         SSLFIPS(NO)
   SSLKEYR(/var/mqm/qmgrs/MQMQGR9/ssl/fresh/ib9keystore)
   SSLRKEYC(0)                             STATACLS(QMGR)
   STATCHL(OFF)                            STATINT(1800)
   STATMQI(OFF)                            STATQ(ON)
   STRSTPEV(ENABLED)                       SUITEB(NONE)
   SYNCPT                                  TREELIFE(1800)
   TRIGINT(999999999)                      VERSION(09000400)
   XRCAP(NO)
   
   
 ------------------------------
 DISPLAY CHANNEL(CHANNEL1)
     2 : DISPLAY CHANNEL(CHANNEL1)
AMQ8414I: Display Channel details.
   CHANNEL(CHANNEL1)                       CHLTYPE(SVRCONN)
   ALTDATE(2019-09-11)                     ALTTIME(13.00.15)
   CERTLABL( )                             COMPHDR(NONE)
   COMPMSG(NONE)                           DESCR( )
   DISCINT(0)                              HBINT(300)
   KAINT(AUTO)                             MAXINST(999999999)
   MAXINSTC(999999999)                     MAXMSGL(4194304)
   MCAUSER( )                              MONCHL(QMGR)
   RCVDATA( )                              RCVEXIT( )
   SCYDATA( )                              SCYEXIT( )
   SENDDATA( )                             SENDEXIT( )
   SHARECNV(10)                            SSLCAUTH(REQUIRED)
   SSLCIPH( )                              SSLPEER( )
   TRPTYPE(TCP)

**Comment by ibmmqmet** [comment]
The connection request is not being made because of an error in the MQCD structure. It is not getting anywhere near the qmgr. It is likely that an version of the structure is being used that is not known by the MQ libraries.

Given your previous issue, I bet you are **still** referring to a downlevel version of the MQ client code. Use setmqenv and/or LD_LIBRARY_PATH to make sure you are using a current level. And get rid of the old, unsupported, version so you don't continue to hit this kind of problem.
