### ISSUE TITLE
Permission denied when building using docker

### ISSUE THREAD

**Issue by Purneau** [ibm-messaging/mq-metric-samples#72]
Just a remark: 

Today I was trying to build the mq_prometheus binaries using the docker scripts (buildMonitors.sh). 
On the final part (during the actual build) it threw `permission denied` errors for everything under `/go` even when running the container as root. 
This led me to believe the issue is related to the volume mount of the output dir. Running the `docker exec` command with `--privileged` did the trick.

**Comment by ibmmqmet** [comment]
OK. Thanks for letting me know. I'll add a note to the README as a hint in case anyone else sees this. It might be that setting a different OUTDIR (in `common.sh`) would also handle it.
