### ISSUE TITLE
mq_prometheus: only qmgr_ metrics exposed , queue_ channel_ subscription_ etc. missing

### ISSUE THREAD

**Issue by Purneau** [ibm-messaging/mq-metric-samples#73]
We recently compiled the `mq_prometheus` binary and now try to use it to scrape the metrics.

Some info: 
```
[<username>@<hostname> errors]$ cat mq_prometheus.out
IBM MQ metrics exporter for Prometheus monitoring
Build         : 20210609-133045
Commit Level  : a590a3e
Build Platform: Linux/x86_64
```

The binary is running with these parameters:
```
/opt/mqm/mq_prometheus/bin/mq_prometheus -ibmmq.queueManager=<QM name> -ibmmq.monitoredQueues=* -log.level=error -ibmmq.httpListenPort=9158
```

When we call the metrics endpoints, **we are missing all queue specific metrics** (see attached file). 
In the DEBUG logging, we see nothing worrying (also attached).

**Can you please assist what we could look into to get all queue/channel related metrics visible?**

[MQPrometheus_debug.txt](https://github.com/ibm-messaging/mq-metric-samples/files/6655259/MQPrometheus_debug.txt)
[metrics endpoint output.txt](https://github.com/ibm-messaging/mq-metric-samples/files/6655277/metrics.endpoint.output.txt)

**Comment by ibmmqmet** [comment]
The first file shows only a single collection interval, when almost all collected data is deliberately discarded. Data would only start to appear from the second collection. 

Also remember that the collector only makes its data available to a single consumer. Running curl or (as several people have run into before) a second instance of prometheus, will take any collected data away from a primary database.

You have also set `useStatus` to `false` which means that none of the metrics from DIS QSTATUS/CHSTATUS will be collected; you will only get the metrics from resource publications (ie queue and qmgr data only).

**Comment by Purneau** [comment]
Thank you @ibmmqmet 

`useStatus` to True was what we were looking for. Closing issue.
