### ISSUE TITLE
Impossible to build offline

### ISSUE THREAD

**Issue by anolting** [ibm-messaging/mq-metric-samples#74]
Hi,

I run into the problem that for aws the build process is looking for the file github.com/aws/aws-sdk-go/go.mod which is not found.
At this point the build process ends as go is not able to check the aws sdk version -> 

`go: github.com/aws/aws-sdk-go@v1.37.23: reading github.com/aws/aws-sdk-go/go.mod at revision v1.37.23: unknown revision v1.37.23`

Best Alex

**Comment by ibmmqmet** [comment]
If you use `go build -mod=vendor`, as is done in the _scripts/buildInDocker.sh_ file then it shouldn't need to go to the network.

**Comment by anolting** [comment]
Hi Mark

thanks for your help. I can compile now.
BR Alex
