### ISSUE TITLE
Support for InfluxDB version 2.0

### ISSUE THREAD

**Issue by Ronmck** [ibm-messaging/mq-metric-samples#76]
Will you be adding support for  InfluxDB version 2.0 ?
version 2 now uses a token to connect and the API has changed.

**Comment by ibmmqmet** [comment]
It's on the list - but it's not just a change to the API. All the environment around it, including how to have a containerised test environment and the query language from grafana has also changed. so it's taking longer than I'd hoped.

**Comment by ibmmqmet** [comment]
Available in latest version
