### ISSUE TITLE
Question: Is there a possiblity to get rid of certain subscriptions especially DISK and CPU?

### ISSUE THREAD

**Issue by manwe81** [ibm-messaging/mq-metric-samples#77]
Hello Mr. Taylor,
is there currently any possibility to limit the subscriptions? Especially for us there is no need that mq_prometheus collects CPU and DISK data.
Thanks in advance for your reply.

best regards
Manuel

MO71 Qm: DEV9D1DE Subscription Status List Export - 25th August 2021

QMgr     Sub Name                                                                                                                                                                                         Type  Durable Subscription ID                                  Topic String                                                                                 
======== ================================================================================================================================================================================================ ===== ======= ================================================ ============================================================================================ 
DEV9D1DE                                                                                                                                                                                                  API   No      414D51204445563944314445202020205A4A0861CA2A0C23 $SYS/MQ/INFO/QMGR/DEV9D1DE/Monitor/CPU/QMgrSummary                                           
DEV9D1DE                                                                                                                                                                                                  API   No      414D51204445563944314445202020205A4A0861CC2A0C23 $SYS/MQ/INFO/QMGR/DEV9D1DE/Monitor/CPU/SystemSummary                                         
DEV9D1DE                                                                                                                                                                                                  API   No      414D51204445563944314445202020205A4A086158840A23 $SYS/MQ/INFO/QMGR/DEV9D1DE/Monitor/DISK/Log                                                  
DEV9D1DE                                                                                                                                                                                                  API   No      414D51204445563944314445202020205A4A086156840A23 $SYS/MQ/INFO/QMGR/DEV9D1DE/Monitor/DISK/QMgrSummary                                          
DEV9D1DE                                                                                                                                                                                                  API   No      414D51204445563944314445202020205A4A086154840A23 $SYS/MQ/INFO/QMGR/DEV9D1DE/Monitor/DISK/SystemSummary

**Comment by ibmmqmet** [comment]
You can select a subset of the available subscriptions for queue metrics (the `queueSubscriptionSelector` config attribute) but there's no subset option for the qmgr level. Because that only creates a relatively small number of subs, it didn't seem worthwhile to add even more options.

**Comment by manwe81** [comment]
Hello Mr. taylor, thx for the reply. Is there any documetation or example how to setup this around?
