### ISSUE TITLE
Programatically change name of a Data dictionary 

### ISSUE THREAD

**Issue by Blessvskp** [ibm-messaging/mq-metric-samples#79]
Using Python 3.9.6 in Windows 10.
I am developing a data frame  that contains 500 rows and 120 columns. The data is downloaded and stored in a dictionary that is updated with data from subsequent iterations, in steps, by appending method.  

In order to identify the time of downloading data, I want to incorporate time (by formatting time and concatenated it to a alphabet to get a new dictionary name)  into the name of the dictionary.
For simplicity, I am giving here the code for only two data sets.

code:

    import pandas as pd
    import numpy as np
    import VName.py
    from nsetools import Nse
    nse = Nse()

    S30=['ABB','ZYDUSWELL']
    def to_upper(S30):
       S30n = []
       for l in S30:
       	   S30n.append(l.upper())
       return S30n

    S30n = (to_upper(S30))
    
    pcm30 = {stock:nse.get_quote(stock)['pChange'] for stock in S30n}
    pcm30

    from datetime import datetime
    from datetime import time as tm

    now=datetime.now()
    ntmfmt1=now.strftime('%H%M')
    x=ntmfmt1
    y='pCh'
    x=str(x)
    if len(x)==3:
        x='0'+x
    elif x:
       pass

    a=str(x)
    z=y+a

After running the above code 

    print(pcm30)
    {'ABB': '-0.92', 'ZYDUSWELL': 2.05}

    print(z)
    'pCh0109'

Now I want to programatically change the name of the dictionary from 
    'pcm30' 
to
     'pCh0109'.
How to do it?

**Comment by ibmmqmet** [comment]
nothing to do with this repo
