### ISSUE TITLE
Please enumerate list of permissions required

### ISSUE THREAD

**Issue by irl-segfault** [ibm-messaging/mq-metric-samples#83]
Hello!

In getting this set up, I ran into a few permissions issues.   I increased the permissions of the `app` user (the user I'm using to connect) in a few different spots to get this working.

In the README, I did not see any mention of which permissions are required and for what -- is the expectation that users of this library are connecting via the `admin` user?  In general, would you be able to enumerate all of the permissions a user needs just to interact with the default system objects (not any user created channels/queues).

The permissions errors I hit, in order were

1) ```mq-metric-prometheus | time="2021-11-09T19:12:39Z" level=error msg="Connection to QM1 has failed. Cannot open queue SYSTEM.DEFAULT.MODEL.QUEUE : MQOPEN: MQCC = MQCC_FAILED [2] MQRC = MQRC_NOT_AUTHORIZED [2035]"```

Solutions was to add Display permissions to the app user for the SYSTEM.DEFAULT.MODEL.QUEUE model queue.

2 )```mq-metric-prometheus | time="2021-11-09T19:14:51Z" level=error msg="Connection to QM1 has failed. Error subscribing to topic '$SYS/MQ/INFO/QMGR/QM1/Monitor/METADATA/CLASSES': MQSUB: MQCC = MQCC_FAILED [2] MQRC = MQRC_NOT_AUTHORIZED [2035] "```

Solution was to add a new topic auth record for user `app` to have Subscribe permissions on this topic.

3) ```mq-metric-prometheus | time="2021-11-09T19:30:12Z" level=error msg="Connection to QM1 has failed. PCF command MQCMD_INQUIRE_Q_NAMES [18] failed with CC MQCC_FAILED [2] RC MQRC_NOT_AUTHORIZED [2035]"```

Solution was to add Display permissions to user `app` for the QM1 queue manager.

Thanks as always!

**Comment by ibmmqmet** [comment]
Just about all management and monitoring solutions tend to assume use of some kind of administrative id. Not necessarily `mqm` (in MQ's case) or `root` (for an OS monitor) but something with similar authorities. And when the monitor is started automatically as part of the qmgr startup, then it always inherits those admin authorities automatically anyway.

It is clearly possible to explicitly add just the specific permissions needed for a particular operation to a non-admin account, as you have found, but those permissions often need to be extended for new features. Either as features are added to the product or monitor, or you configure additional monitoring options. Which tends to lead to more/different monitoring needed for security failures, so it's easier to just make the admin assumption. 

When looking at permissions for admin actions, I often start with the `/opt/mqm/samp/bin/amqauthg.sh` example script and adjust it to any specific requirements. I'd expect the "read-only" path in that script would be sufficient here.

**Comment by irl-segfault** [comment]
ah, makes sense.  Thank you as always :)
