### ISSUE TITLE
Building on z/OS (USS)

### ISSUE THREAD

**Issue by bikashdube** [ibm-messaging/mq-metric-samples#9]
Trying to install mq_prometheus to run in the z/OS unix system services for monitoring queue managers running on the mainframe. I have successfully built go and gofmt using the z-os/go repo https://github.com/zos-go/go 

The version of go on that repo is quite outdated (1.6), so I have requested the port to be updated. Meaning when I am trying to build mq_prometheus (latest pulled version), I get the following error

```go build -o bin/zos_s390x/mq_prometheus src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/*.go```

src/github.com/ibm-messaging/mq-metric-samples/cmd/mq_prometheus/exporter.go:33:2: no buildable Go source files in /fidglbl/perfwas/go-zos/src/github.com/ibm-messaging/mq-metric-samples/vendor/github.com/ibm-messaging/mq-golang/ibmmq

**Comment by bikashdube** [comment]
Nevermind, I see that mq_prometheus accepts ```-ibmmq.client``` flag to go with the MQSERVER environment variable to connect to remote queue managers. (It probably needs to be documented :))
We can close the issue with any closing comments if you have

**Comment by ibmmqmet** [comment]
There's already some information in the README about this, but next time I do an update to the package I'll try to make it c;learer.
